### ISSUE TITLE
error message 报错

### ISSUE THREAD

**Issue by kamanqi** [juzeon/SydneyQt#1]
![image](https://github.com/juzeon/SydneyQt/assets/13653035/e72f3af8-82ec-442f-bd1c-6876629d8447)
这个项目很棒，集中了其他几个GUI的优点，作者用心了但是这个报错 一直出现 ，这是什么问题？  另外想请作者在proxy这里默认写一个示范作为格式样板，我没搞明白这里应该怎么填 只填端口？还是127.0.0.1：8080这样的完整地址？又或者要带上http开头，一直报message错误我也无法验证到底该什么格式的填法，还请作者大佬指教

**Comment by juzeon** [comment]
这个错误应该是网络问题，代理的写法举例：

```
http://127.0.0.1:7890
# or
socks5h://127.0.0.1:7890
# or
socks5://127.0.0.1:7890
```

**Comment by kamanqi** [comment]
> 这个错误应该是网络问题，代理的写法举例：
> 
> ```
> http://127.0.0.1:7890
> # or
> socks5h://127.0.0.1:7890
> # or
> socks5://127.0.0.1:7890
> ```


非常感谢大佬的回复和解释 ！真棒！
