### ISSUE TITLE
macOS 上无法显示 Snapped Content

### ISSUE THREAD

**Issue by Xicrosoft** [juzeon/SydneyQt#102]
## 系统信息
macOS 14.0 Developer Beta 版 (23A5301h)[非最新版本]

## 问题描述
单击 Snap 后一直处于 Loading 状态

<div align=center>
<img width="962" alt="截屏2023-09-18 下午9 41 13" src="https://github.com/juzeon/SydneyQt/assets/90536984/be88321e-b052-4a2f-9921-08d67513cebb">
</div>

<div align=center>
<a href="https://xicro-my.sharepoint.com/:i:/g/personal/oss_xicro_pp_ua/EbM2exgUtlpPsPBaRvOga1ABYoqnkgTbfUZDGaT9xvGUpQ?e=WPrzsD"><img width="200" alt='OneDrive Download Badge' src="https://xicro-my.sharepoint.com/personal/oss_xicro_pp_ua/_layouts/52/download.aspx?share=EcDQt0YM1p9GpV1sExMaIvcBCbpDWW7GM3-fC4XdhyJv9A"></a>
</div>

**Comment by juzeon** [comment]
没有macos环境，暂时无法调试。
