### ISSUE TITLE
无法获取 Bing Chat Enterprise (BCE) 的用户信息

### ISSUE THREAD

**Issue by Xicrosoft** [juzeon/SydneyQt#103]
## 系统信息
macOS 14.0 Developer Beta 版 (23A5301h)[非最新版本]

## 问题描述
Cookies 文件正常、可以正常进行对话，但无法识别用户，显示 `Cookie is malformed`
我想可能是还未适配 BCE 的 Cookies

<div align="center">
<img width="412" alt="截屏2023-09-18 下午10 32 24" src="https://github.com/juzeon/SydneyQt/assets/90536984/7c25c851-c308-42ec-869d-4723e8e2f0b0">
</div>

<div align="center">
<a href="https://xicro-my.sharepoint.com/:i:/g/personal/oss_xicro_pp_ua/EVQxRjcPD7ROvurAjcOCyh0BMA83eQ3RvnxkReovVUX0BA?e=I5QAWP"><img width="200" alt="Badge" src="https://user-images.githubusercontent.com/90536984/268679291-66ddb3b2-5d2e-4451-84e8-967db2d332dd.svg"></a>
</div>

**Comment by juzeon** [comment]
目前Cookie Checker使用的是cookie中`_U`这个鉴权key来判断登录状态的。不知道企业版的鉴权key是哪个。
