### ISSUE TITLE
来源引用依然无法完全显示

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#106]
之前这个问题已经修理过一次（上次是完全无法显示任何来源），不过应该还是没修完整。

官方bing显示来源一般是在对话的底部，分成12 3 4 5 6 7 等等。
但是在实际的对话中，往往只会使用1234 ，部分是让用户参考，但不会在对话中直接使用。

我希望的情况，其实是官方那种引用尽可能全面的显示，因为探索这些没有提及的英文资料也是挺有意思的。
毕竟，用Ai搜索一个大问题，就是Ai天天偷懒，探索的深度远远不足。

具体可以看看下面这个对话。

第一个对话：可以发现客户端只能看到4个来源乘以2，但是实际上的来源很可能是远远不止。

txt里面，bing在末尾使用了7号来源，但是我没看到7号来源，也跟第二个3号对不上。要么是出现了幻觉，要么真的是丢了点引用吧。

[2023-09-21还是无法完整显示搜索来源.txt](https://github.com/juzeon/SydneyQt/files/12680972/2023-09-21.txt)

第二个对话：Bing提到可以查看19号来源，但是显然客户端里面没有这个19号来源存在，连总的来源都没有19个。

客户端给出来的编号还是123 ，123 这样重复了好几次的，编号看起来也是乱的。

[2023-09-21查理芒格的19号来源.txt](https://github.com/juzeon/SydneyQt/files/12681083/2023-09-21.19.txt)

**Comment by juzeon** [comment]
有时候Bing会编造来源，即使关掉搜索很多时候仍然会引用来源。

#search_results 提取的已经是所有接口返回的来源了。

**Comment by riverai** [comment]
> 有时候Bing会编造来源，即使关掉搜索很多时候仍然会引用来源。
> 
> #search_results 提取的已经是所有接口返回的来源了。

这里还有一个问题。能否让客户端显示的来源的顺序和网页版类似？
现在如果Ai搜索了超过一个query，那么客户端看到的引用编号依然是循环的12 3 4 ，但是网页版是把他们合并计数的，而且正文似乎也是用的这个顺序来引用。

现在如果它说请看4号来源，我都不知道到底说的是哪个第4号。

**Comment by riverai** [comment]
@juzeon 听说这个是按照数组来返回的，而且数组本身也是有编号的，所以应该做加法之后是能直接对应上的。
现在用turbo搜索，可以约定必须查询5个不同query，返回22个以上的结果，而且turbo幻觉率目前很低，响应速度又快到不可思议。
在进行广撒网的搜索的时候，那体验真的是爆表了。

比如我今天想查询几个主题，想试试能不能用来水一篇文，于是就主题-分主题-混合不同主题，让turbo进行过好几次搜索，每次都能查阅到5-25个搜索结果的大概内容。

不过还是遇到了老问题，搜索编号都是乱的。

**Comment by juzeon** [comment]
Resolved: 7bb16bd16e433a4b731fc699032551e0db8d10b3...174f41f0a81d87bd5a11142ddc4a2a04b706dc74
