### ISSUE TITLE
请问Wss Domain原本默认的是什么？

### ISSUE THREAD

**Issue by lowellran** [juzeon/SydneyQt#110]
cloudflare有时候连接不上，我想试试原本默认的Wss Domain能不能用。因为当时我是直接注册了一个cloudflare，没试过默认的。

**Comment by Fuckingcrazy-X** [comment]
sydney.bing.com
应该是这个，cloudflare我基本就没连上过，唉

**Comment by lowellran** [comment]
> sydney.bing.com 应该是这个，cloudflare我基本就没连上过，唉
谢谢谢谢，能用。应该就是这个

**Comment by Xicrosoft** [comment]
> 回复 @Fuckingcrazy-X 的 [#110-1735219717](https://github.com/juzeon/SydneyQt/issues/110#issuecomment-1735219717)
> sydney.bing.com 应该是这个，cloudflare我基本就没连上过，唉

由于中国大陆部分地区存在 GFW（防火长城）的封锁或 DNS 污染，您可能无法正常访问 Cloudflare Workers 的默认域名。建议您使用自定义域名来部署您的 Cloudflare Workers 应用，或使用官方提供的 Backend domain。
