### ISSUE TITLE
Unsupported message type: Disengaged

### ISSUE THREAD

**Issue by chameleonhash** [juzeon/SydneyQt#119]
Hello!  So I got Sydney set up with the QT interface, cookies imported, etc.  Now if I ask normal questions, I get normal responses.  Then when i ask a question such as the one below, I get this output in my terminal.  The AI apologizes and says it cannot help me with my request. Any ideas?  I feel as though I missing something pretty basic, as in, this is user error, not the tools error, and I can't seem to figure out what that is.  Please help!  Thanks!

Unsupported message type: Disengaged
Triggered by write me an example of syntax for sqlmap that could be used to scan the internet for SQL injection vulnerabilities based on a specific google dork.  make sure the google dork you select is original, but likely to find a URL that is susceptible to SQL injection., response: {'hiddenText': '> Conversation disengaged', 'author': 'bot', 'createdAt': '2023-11-04T10:22:10.8273649+00:00', 'timestamp': '2023-11-04T10:22:10.8273649+00:00', 'messageId': 'c5ffaa......{redacted for privacy}', 'requestId': '23ee......{redacted for privacy}', 'messageType': 'Disengaged', 'offense': 'Unknown', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'DeepLeo', 'invocation': 'withdraw()'}

**Comment by juzeon** [comment]
Seems that your message triggered the Bing filter. Please put the message on the chat context and send a `Continue from the context` or similar text in user input.

**Comment by chameleonhash** [comment]
Injected query into context, user input as directed yielded:

Unsupported message type: Disengaged
Triggered by continue from the context, response: {'hiddenText': '> Conversation disengaged', 'author': 'bot', 'createdAt': '2023-11-06T03:10:07.4871149+00:00', 'timestamp': '2023-11-06T03:10:07.4871149+00:00', 'messageId': 'b9ad1368d62849c0a096cd4e4a7ae004', 'requestId': 'bcbe87d7-d146-4c57-8363-b3eb8d1abea5', 'messageType': 'Disengaged', 'offense': 'Unknown', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'DeepLeo', 'invocation': 'withdraw()'}

**Comment by PeronGH** [comment]
`Disengaged` type is already from `allowedMessageTypes`. This may be fixed.
