### ISSUE TITLE
Cookie-Editor 需要获取所有站点的权限才能导出所有所需的 Cookies

### ISSUE THREAD

**Issue by Ayx03** [juzeon/SydneyQt#120]
即在这一界面必须点击 All sites
![](https://github.com/juzeon/SydneyQt/assets/75155322/a4d48ab3-3c36-4a4c-8511-a5d0bb79129f)
如果点击 This site 它只能获取一两个 Cookie(s)，包括 `ai_session`、`ai_user`，这也是导致 `Cookie is malformed` 和一直出现 `User needs to solve CAPTCHA to continue` 的原因
![](https://github.com/juzeon/SydneyQt/assets/75155322/e9c8d528-c38a-4965-9288-0a7bb6d7dcde)
猜测可能与访问 `bing.com` 会自动跳转到 `www.bing.com`，而所需的 `_U` 等 Cookies 在 `bing.com` 下有关？
![图片](https://github.com/juzeon/SydneyQt/assets/75155322/4b9f81ba-f3ff-44bf-b0fb-8cfc0a7292c1)

**Comment by Ayx03** [comment]
#121

**Comment by juzeon** [comment]
The corresponding PR has been merged.

**Comment by Ayx03** [comment]
此问题已在 https://github.com/Moustachauve/cookie-editor/pull/169 中被修复，等待新的发行版。
