### ISSUE TITLE
continue时重复整个段落有个解决方法

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#123]
不管是用手动的快捷输入“从这里继续”，还是用“#continue”，还是要求必须“从最后一个文字或者单词，而不是段落”开始，bing现在都有相当的可能性把整个段落或者回复的模块重新回复一次，而不是真的从最后一个字母开始。

bing这种操作，轻轻松松就能将之前的几百个字再说一次。
不知道你遇到过没有？

我前两天发现一个方法，可以规避这点。
就是将”从这里继续“后面添加一行字：”从这句话的结尾开始：上次bing输出的最后一句话“。

这样就可以避开开始的问题。

唯一的问题就是，这样需要手动操作，如果能在快捷回复里面也使用变量，自动输入最后这句话的自动变化就好了。

**Comment by juzeon** [comment]
快捷回复里有个Edit的选项，可以编辑快捷回复的备选列表。

**Comment by riverai** [comment]
> 快捷回复里有个Edit的选项，可以编辑快捷回复的备选列表。

我知道这个。
但是这里面的内容是写死的，现在需要的是”动态“的回复。比如总是截取bing最后回复的10个字，让它从这里开始。
这样是为了防止bing在”继续“的时候，重复输出整个回答模块。
