### ISSUE TITLE
能否支持更多的OpenAI API的参数

### ISSUE THREAD

**Issue by tastypear** [juzeon/SydneyQt#127]
目前接口只能设置`temperature`，现在有很多模型提供OpenAI API形式的接口（例如 llama.cpp-python server），如`presence_penalty`、`frequency_penalty`、`stop` 等等。能否增加更多参数的设置选项。

**Comment by juzeon** [comment]
Resolved: cb769d10419e7fdc711470eeee72f939d52d3c8e
