### ISSUE TITLE
TypeError: Chatbot.create() got an unexpected keyword argument 'cookie_path'

### ISSUE THREAD

**Issue by kamanqi** [juzeon/SydneyQt#13]
![image](https://github.com/juzeon/SydneyQt/assets/13653035/9caed767-e7f6-450b-83bd-623ba5952d4d)
 
真的很喜欢这个项目，是众多bing项目中感觉最适合自己风格的，但是无奈自己菜，我这又是遇到什么问题了？以下报错
```
PS D:\py\SydneyQt-master - up> python main.py
Traceback (most recent call last):
  File "D:\py\SydneyQt-master - up\main.py", line 252, in send_message
    chatbot = await Chatbot.create(cookie_path="cookies.json", proxy=proxy if proxy != "" else None)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Chatbot.create() got an unexpected keyword argument 'cookie_path'

```
补充下我做了什么：一切正常，然后今天看到了有更新，大喜，重装了新版，然后就这样了，老版没删，连cookie都是一样的，居然老板的可以使用。我们什么都没变，难道是新版的问题？看提示是cookie路径有问题？老版的也是一样的位置放的一样的cookie. 然后重装各种实验，还是无解，但是推测应该是新旧版哪里对cookie设置不同，可是新版貌似安装方法也没有变啊？于是十分不好意思的又来请教。。。。

旧版截图：

仍然在使用，但是俺也想用新版啊
![image](https://github.com/juzeon/SydneyQt/assets/13653035/45d4b69d-d02e-4eb9-a6ed-fb22b8270a53)

**Comment by juzeon** [comment]
新版EdgeGPT更新了cookie的传入方式，旧的方式不能用了。刚刚修复了这个问题。 f1ec8db20955ba153f19a45f84c294df00164e83

**Comment by kamanqi** [comment]
已经更新，确实解决了，谢谢大佬！
