### ISSUE TITLE
config.json迁移到2.0

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#130]
json文件内容的格式我看了下有的地方改变了，直接用原来的是不行的。

不知道这些改变有多大？是否有可能将原来的文件稍微做下修改就能适配到2.0呢？

**Comment by juzeon** [comment]
有改动的数据量比较大的地方主要是`presets`、`workspaces`，原来是键值对现在改成数组了。可以对照着改一下。另外`conversation_style`现在统一都是首字母大写。

**Comment by riverai** [comment]
终于修改好了，全程用bing自己来写代码，完成了自动转换原来的Workspace数据和preset数据到新的格式，然后将这些格式手动复制粘贴到新的文件。
算是90%的自动化。


然后发现，写出来的代码能否运行真的看运气。有的时候写出来的代码不好，直接退回到某个问题，然后重新问问题是最好的。

**Comment by riverai** [comment]
我写了下经验
https://github.com/juzeon/SydneyQt/discussions/132

还有人问的话让他们看这个就行了。
