### ISSUE TITLE
切换界面会无响应或者无法操作

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#133]
现在，最新版，使用起来有问题。

在bing说话的时候，我选择按一下alt+tab切换窗口，这时候qt程序就会失去响应。
![image](https://github.com/juzeon/SydneyQt/assets/3251548/eb1aefb9-f4aa-4313-a22a-f8cfcaed78f4)

自然，也就不能点击stop按钮了。
想要操作的话只能等待bing将话说完。

**Comment by juzeon** [comment]
这边不能复现。猜测是否是笔记本开启了省电模式等，导致切换到后台时webview被休眠？

如果可以的话能否按照<https://github.com/juzeon/SydneyQt#build>的步骤，使用`wails dev`打开开发模式，重复一下操作然后贴一下控制台输出的完整日志？

**Comment by riverai** [comment]
> 这边不能复现。猜测是否是笔记本开启了省电模式等，导致切换到后台时webview被休眠？
> 
> 如果可以的话能否按照https://github.com/juzeon/SydneyQt#build的步骤，使用`wails dev`打开开发模式，重复一下操作然后贴一下控制台输出的完整日志？

之前可以稳定重现的。
刚才测试了确实是节能模式问题。
我之前用了“节能之星X”程序。现在将SydneyQt-windows-amd64.exe添加到白名单之后，问题严重程序下降了。

--更新下。不是完全消失，而是可以很快“恢复响应”。

**Comment by riverai** [comment]
> 这边不能复现。猜测是否是笔记本开启了省电模式等，导致切换到后台时webview被休眠？
> 
> 如果可以的话能否按照https://github.com/juzeon/SydneyQt#build的步骤，使用`wails dev`打开开发模式，重复一下操作然后贴一下控制台输出的完整日志？

用能源之星X的白名单，依然有概率重现这个问题。在切换回来之后可以几秒钟内恢复。
