### ISSUE TITLE
新的会话默认的new chat作为标题不太好

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#134]
每一个都是new chat，现在是连编号都没了。以前的话至少还有个编号。

另外，我想问下，bing网页版会有个自动标题生成功能，客户端有可能实现吗？如果不能，有可能通过GPT3.5实现这功能吗？如果是3.5能实现，这操作的消费是多少？如果消费低的话，可以用这个方案。

**Comment by juzeon** [comment]
之后尝试下自动生成标题的方案。
