### ISSUE TITLE
Cookie 检查一直显示成红色

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#137]
![image](https://github.com/juzeon/SydneyQt/assets/3251548/7b62c7f6-3856-4bac-83cb-6398ff9ec6fc)

实际上对话是可行的，所以cookie应该是有效的，但是一直提示错误。除非现在不需要cookie就能对话，那么这里的逻辑就是成立的。

**Comment by juzeon** [comment]
现在有时候确实不需要cookie就可以对话。

**Comment by riverai** [comment]
> 现在有时候确实不需要cookie就可以对话。

更新下测试结果。

刚登录网页版，发现同样的cookie在网页上显示成了“半登录“。不是彻底退出状态，也不是登录状态。这时候点击下网页右上角的”登录“可以一秒内自动登录。
这个状态以前也遇到过，不少人进入了这种”半登录“，所以只能用大概10次对话（在网页上的一个会话内）。只不过只能用10次对话那是以前的，刚才我没留意我在这种状态能用多少次对话。

但是呢，这样的状态在客户端上是可以基本正常使用的。
所谓基本正常，是因为，我发现有一个问题，在这种”半登录“下，相对远远更容易会触发审核停止。
之前只要我问scold down the path of这个习语到底是否存在，就百分百会触发审核，哪怕这个内容写在了system message中。
现在登录之后就可以继续输出回答了。

所以结论是：

有效的登录状态应该是有利于减少严格的审查的。
这里显示红色也确实不能算有问题，除开比较碍眼。
我在点击”登录“后，重新生成了cookie，红色终于变成了绿色了。

**Comment by juzeon** [comment]
感谢分享经验
