### ISSUE TITLE
禁止自动滚动功能实际用起来有性能和其他问题

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#138]
这个功能盼望挺久了，刚才终于有机会试用了下，然后就发现了不少问题。

问题1，这个生效是一次性的，每次bing说话回复我之后，这个状态都会失效。

问题2，点击之后会有严重性能问题。 一旦我开启了“禁止自动滚动”，那么电脑就会瞬间变得卡顿，让我查看文字都变得有点不可能了。
你可以试试滑动滚轮，是否能感受到特别卡顿。

问题3 ，使用之后这个按钮的文字描述会发生错乱。这个直接看图。
![image](https://github.com/juzeon/SydneyQt/assets/3251548/a0c8159d-f813-411f-80f4-66ec5e954dc6)

**Comment by juzeon** [comment]
卡顿和按钮错乱我这边都无法复现，可以录制个视频或gif吗？

一次性是故意设计的，每次重新开始对话都会设置为允许滚动，这是为了跟进到最新的输出。

**Comment by riverai** [comment]
> 卡顿和按钮错乱我这边都无法复现，可以录制个视频或gif吗？
> 
> 一次性是故意设计的，每次重新开始对话都会设置为允许滚动，这是为了跟进到最新的输出。

先来看性能问题吧。录制了一个视频。
这里面的上下滑动，并不是因为我等了很久才滑动一次。我实际上一直在使用滚轮滑动，只不过因为实在太卡了，所以等很久才突然滑动很远的距离。

https://github.com/juzeon/SydneyQt/assets/3251548/f74682ad-14b0-44a8-aada-af4869c174e2

**Comment by juzeon** [comment]
是否和配置文件太大、workspace太多等有关系？尝试一下用全新的、最小配置的文件试试。

**Comment by riverai** [comment]
> 是否和配置文件太大、workspace太多等有关系？尝试一下用全新的、最小配置的文件试试。

新开了一个配置文件，有且仅有一个Workspace，确实是可以流畅滑动不卡顿了，CPU没有观察到明显的暴涨到50%以上占用。
那么现在的问题是为何会出现这种状态，为何以前用原生的就可以用几百个会话，现在会卡顿呢。

**Comment by juzeon** [comment]
应该是web图形比较丰富，需要渲染算力大。之后尝试做一下优化。

**Comment by riverai** [comment]
> 应该是web图形比较丰富，需要渲染算力大。之后尝试做一下优化。

这里有个疑点。不用这功能，虽然说还是不太流畅，但至少还是可以接受的。只要用了这功能，立即变得超级卡顿。
所以这里一个理论上并不特殊的操作，内部到底发生了什么？

**Comment by juzeon** [comment]
按理来说允许滚动开启的时候因为要不断设置滚动条，有增加负担的代码。禁用滚动时反而没有。
