### ISSUE TITLE
程序在任务栏没图标

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#139]
目前程序在任务栏是没有自定义的图标的，让程序看起来有点像三无了。不仅是美观上，辨识度上也差了点。

这可以加上吗？

**Comment by riverai** [comment]
刚发现其实是有图标的，但是一旦”卡死“，”失去响应“，就会没了图标。

变成了这样。
最右边的图标就是QT2.0
![image](https://github.com/juzeon/SydneyQt/assets/3251548/ef76d649-f5a2-4153-988c-7266876522dc)

哪怕”无响应“回到了”有响应”状态，还是这种图标保持了下去。

反正就是这么反复横跳吧。

**Comment by juzeon** [comment]
我这边win10上一直都是有图标的，会不会是win11的bug。

**Comment by riverai** [comment]
> 我这边win10上一直都是有图标的，会不会是win11的bug。

应该还是跟前端太卡有点关系，现在先观察增强前端的性能后的结果吧。
