### ISSUE TITLE
Input error

### ISSUE THREAD

**Issue by G-LJDS2022** [juzeon/SydneyQt#14]
Unterminated string starting at: line 68 column 14 (char 1724)

**Comment by juzeon** [comment]
Hello. Could you give more details on this error? When and where did it happen? Is it reproducible? I'd appreciate it if you could provide some screenshots.

**Comment by G-LJDS2022** [comment]
![微信图片_20230528000703](https://github.com/juzeon/SydneyQt/assets/134282368/8c32f894-f766-4a27-9005-7c7b5673b7a6)

**Comment by juzeon** [comment]
Hello again. Can you provide a terminal output?
