### ISSUE TITLE
试图调用第三方api时直接跳出了（App crashes when using a 3rd party openai api）

### ISSUE THREAD

**Issue by NostalgiaGit** [juzeon/SydneyQt#142]
如题，想在客户端里直接使用一个openai的中转api，填好key和endpoint，backend也选择Openai后，使用时程序直接崩溃跳出了。

在之前原生python的SydneyQt里其实也会报错，在那里使用时会报一个list index out of range的错，如下

list index out of range
Exception ignored in: <async_generator object APIRequestor.arequest.<locals>.wrap_resp at 0x000001D5966D7640>
Traceback (most recent call last):
  File "D:\SydneyQt-master\main.py", line 378, in send_message
    await self.send_openai(text_to_send)
RuntimeError: async generator ignored GeneratorExit

并不是所有三方api都会这样，有的就可以正常使用，但有的就会产生这种问题，请问这是什么原因呢？

另外还想问一下这个客户端对话的原理是什么，会不会相当于每次对话都把聊天界面的历史对话记录打包发送给AI，要是这样的话使用api时是不是会产生大量重复计费的问题？
（主要是很喜欢SydneyQt能上传pdf的功能，所以用openai api时也想在SydneyQt里用 XD）

**Comment by juzeon** [comment]
应该是获取choices数组第一个元素的时候出现问题了。

```
{
    "id": "chatcmpl-abc123",
    "object": "chat.completion",
    "created": 1677858242,
    "model": "gpt-3.5-turbo-1106",
    "usage": {
        "prompt_tokens": 13,
        "completion_tokens": 7,
        "total_tokens": 20
    },
    "choices": [
        {
            "message": {
                "role": "assistant",
                "content": "\n\nThis is a test!"
            },
            "finish_reason": "stop",
            "index": 0
        }
    ]
}
```

按照OpenAI的标准choices数组应该至少有1个元素，但不知道为什么可能有些第三方API这里返回了0元素。

可以方便透露下是哪家第三方API吗，要解决的话可能得看下他们具体的返回体。

---

每次发送都是把所有历史记录一起打包发送，这点其实所有客户端包括官方都是一样的，因为这就是大模型能追溯上下文的原理。

**Comment by NostalgiaGit** [comment]
非常感谢！解决了。
