### ISSUE TITLE
点击上传PDF文件闪退，上传pptx文件file is not a slide xml:ppt/slides/

### ISSUE THREAD

**Issue by DGxg9420** [juzeon/SydneyQt#146]
问题：点击上传PDF文件闪退，上传pptx文件file is not a slide xml:ppt/slides/
补充：上传docx文件没有问题
系统：Windows 11 家庭版 22H2 操作系统版本 22621.2715
SydneyQt: 2.1.3
电脑上用的WPS：
![image](https://github.com/juzeon/SydneyQt/assets/71811502/a737bd44-14d2-44f1-bef8-2c687a94597d)
上传pptx问题截图：
![image](https://github.com/juzeon/SydneyQt/assets/71811502/d525db83-909d-49ec-b4bc-62696ded289a)
上传使用的pdf和pptx文件：
[10085.pdf](https://github.com/juzeon/SydneyQt/files/13632015/10085.pdf)
[测试文件.pptx](https://github.com/juzeon/SydneyQt/files/13632017/default.pptx)

不知道什么因素会影响到软件运行，如果还缺少信息我可以继续提供。

**Comment by juzeon** [comment]
pptx确实是个bug，已经修复，将在下个版本发布。

pdf的bug是所有pdf都会这样吗，还是某些pdf？我这边用你上传的pdf测试是可以正常读取的。

**Comment by juzeon** [comment]
不用了，已经复现成功。

**Comment by juzeon** [comment]
已修复，在下个版本更新。

**Comment by DGxg9420** [comment]
> 已修复，在下个版本更新。

太棒了，辛苦了，效率很高。
