### ISSUE TITLE
关于生成图片，但图片被撤回的问题

### ISSUE THREAD

**Issue by JINGO1234** [juzeon/SydneyQt#147]
希望后续版本能有图片防撤回的功能

**Comment by juzeon** [comment]
可以提供一下能够触发撤回的prompt吗。

**Comment by JINGO1234** [comment]
谢谢。  大概是：泳衣 猫耳 动漫美少女 。不过感觉它这个撤回机制很迷，有的时候会撤回，有的时候不会。

**Comment by juzeon** [comment]
图像撤回是在内部进行的，我们没法获得撤回的内容。
