### ISSUE TITLE
Add Option for GPT-4-Turbo Version

### ISSUE THREAD

**Issue by PeronGH** [juzeon/SydneyQt#148]
It is found that adding `dlgpt4t` to option sets can enable GPT-4-Turbo, which is much more capable and ChatGPT-like. But it is also harder to jailbreak. I think maybe there can be an option for enabling it.

**Comment by PeronGH** [comment]
I've tested the GPT-4-Turbo version on my local build. It has fresher knowledge cutoff (though the system message is not updated and still says its knowledge is up to 2021) and generates much better response (instead of being repetitive like Sydney). But the jailbreak has failed. The GPT-4-Turbo version of Bing Chat is likely using the same model as the OpenAI API, which is very difficult to jailbreak (You can have jailbreak system message in API, but the model doesn't follow). Considering the trade-off, I don' think it should be the default option for this project, but it can be a good alternative to the original ChatGPT.

**Comment by juzeon** [comment]
Thanks. The new option will be shipped with the next verison.
