### ISSUE TITLE
turbo用起来怎么像是精确版

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#150]
文字输出特别少，而且特别偷懒，吓死人那种。

对比下创意版turbo输出质量。

![image](https://github.com/juzeon/SydneyQt/assets/3251548/f60eebb6-b838-4864-a9a3-bc6b30394a37)

以及非turbo上的创意版 
<img width="766" alt="5f64fa9c49faa0f55614bd3c578c5f6" src="https://github.com/juzeon/SydneyQt/assets/3251548/2cdbf469-758d-482e-b38d-0516eb1225c2">

![image](https://github.com/juzeon/SydneyQt/assets/3251548/2a1fa340-e519-4d0a-b09e-bc4f3700f767)

我已经确定，我使用了相同的提示词+提问。

你们试过turbo吗，turbo就是这种风格吗？
如果这是正常的，那么只能说：千万别用turbo，会变得不幸。

**Comment by juzeon** [comment]
确实是模型的问题，谷歌一下`gpt-4-turbo becomes lazy`可以找到一堆新闻。

**Comment by NostalgiaGit** [comment]
的确有可能被微软调过，我也感觉它有点言简意赅。不过Bing创意模式本身也是啰嗦到吓人的那种，所以两个对比起来反差有点大。

我拿你这个问题一模一样的字粗试了几个模型，只问了一次，模型给我回复的字数从多到少依次是Bing创意638字，两个正规渠道的普通GPT4一个482字一个433字，Bing精确291字，Bing Turbo模式236字。很遗憾我没有权威的试用1106-preview的渠道，手头试了两个中转api，表现倒是比这个Bing Turbo好一些，一个回复672字一个513字，但我很难确定它们是不是真的1106。

目前感觉Bing Turbo模式执行一些需要写作的任务表现确实欠佳，比如我让他按照我的Prompt模板来总结pdf，怎么说呢感觉要点似乎该提也提了，但结构不太好，总结不够细，比如我会让他专门提炼全文涉及数据的地方，它会说“文章提供了全年xxx的数据”，但不会把数据写出来。而以往GPT4总结都会详细写出来，还真就有点那个偷懒的感觉。不过我只测了一次，不排除是偶尔状况。

执行其他任务还行，比如我让它润色我的文本，挑挑语法错误，改改措辞什么的，这个似乎还行，可能是因为这没要求它主动创作什么，只是基于我的文本修改吧，而且我给的prompt对它要做的事规范也比较详细。

不过这个Bing Turbo至少确实是GPT-4的逻辑水准，而且知识库也符合1106-preview官方所说的到2023年4月，我试过它若干问题，它知道今年3月23日TikTok CEO出席美国听证会的事，而不知道7月份Twitter改名为X的事（本来就不应该知道，问这个只是为了确认它没有悄悄联网）。

相比之下，Bing创意现在逻辑水准时不时会弱于普通GPT4的表现，比如那个经典的鲁迅周树人问题，我刚问一次它又开始胡编了，但它应该也不是3.5，至少一些3.5现在还不能正确回答的测试题它可以。Bing精确就好一些，在某次更新后一直维持GPT-4的水准，嗯，起码鲁迅问题没失手过，虽然比其他官方渠道的GPT-4似乎还是差那么一点（但很多时候感受并不明显）。

**Comment by kamanqi** [comment]
我也发现了 ，turbo模式下，回答都不理想，我猜是不是微软给turbo增加了更多的限制，所以我一直在使用普通模式。
