### ISSUE TITLE
Error: open config.json: read-only file system Details: file(/Users/runner/work/SydneyQt/SydneyQt/config.go), line(185).

### ISSUE THREAD

**Issue by aodrasa** [juzeon/SydneyQt#151]
Getting this error. Any idea how I'd resolve this? Running on MacOS 14.1.1 M1 Pro

![Screenshot 2023-12-14 at 12 57 16 pm](https://github.com/juzeon/SydneyQt/assets/121209163/394c7c80-562e-4072-890b-79a763d79501)

**Comment by juzeon** [comment]
Need more investigation to resolve problems related to macOS as I do not have an Apple computer. In the meantime you may need to build it yourself referring to https://github.com/juzeon/SydneyQt#build

**Comment by riverai** [comment]
> Need more investigation to resolve problems related to macOS as I do not have an Apple computer. In the meantime you may need to build it yourself referring to https://github.com/juzeon/SydneyQt#build

估计是将1.0的config.json放在了2.0的文件夹，直接打开有可能就会这样报错吧。我猜的，不知道是不是。

**Comment by juzeon** [comment]
> > Need more investigation to resolve problems related to macOS as I do not have an Apple computer. In the meantime you may need to build it yourself referring to https://github.com/juzeon/SydneyQt#build
> 
> 估计是将1.0的config.json放在了2.0的文件夹，直接打开有可能就会这样报错吧。我猜的，不知道是不是。

Nar, seems something related to the Apple filesystem, and permission things.

**Comment by riverai** [comment]
@juzeon  我复现了下。
安装pkg会提示不支持打开，然后去"系统和隐私“看已经阻止的，可以运行pkg运行。
然后就是安装。
安装好了之后会出现qt.app。 
运行就会出现这里的readonly 提示。

**Comment by deepc0py** [comment]
I'm facing the same issue even after building it myself on an M1 Mac

**Comment by zipos** [comment]
I didn't build for myself but as mentioned above it would probably give no results. I'm willing to help with testing to resolve this bug. I'm using a 2020 Macbook Pro M1 16/512.

**Comment by deepc0py** [comment]
The installer creates folder /Users/runner but doesn’t set the permissions properly. Tried chown and taking ownership in the MacOS properties dialog but no dice. Will need to make changes to have the installer make use of /Library/ApplicationSupport

**Comment by juzeon** [comment]
Fixed in 154892c50758ccc770282034234cab438dddc8dc

**Comment by juzeon** [comment]
Fixed in 154892c50758ccc770282034234cab438dddc8dc

**Comment by juzeon** [comment]
Hi participants. This issue should be fixed after v2.4.3. Please give it a try :)
