### ISSUE TITLE
增加对gpt4v的支持，图片上传

### ISSUE THREAD

**Issue by XianYuDaXian** [juzeon/SydneyQt#154]
gpt4v现在已经公测了，希望能添加支持，现在点击上传图片回复看不到图片

**Comment by juzeon** [comment]
上传的图片不会显示在Chat Context中，但实际是有效的。

**Comment by XianYuDaXian** [comment]
我的表达有误，是上传图片后gpt回复说抱歉因为是文本模型所以无法查看图片。
![_20231214201037](https://github.com/juzeon/SydneyQt/assets/20138259/df4cff21-b1a9-48ab-9468-6f199477e5eb)

**Comment by juzeon** [comment]
暂时还不支持openai接口的vision，等手上拿到接口试试。
