### ISSUE TITLE
请问可否给出调用webapi的demo

### ISSUE THREAD

**Issue by QiranYC** [juzeon/SydneyQt#155]

**Comment by PeronGH** [comment]
Hi there. You can simply use OpenAI SDK to make use of the webapi. Here is an example using Deno and OpenAI SDK for Node.js.

```ts
import OpenAI from "https://deno.land/x/openai@v4.22.0/mod.ts";

const openai = new OpenAI({
  apiKey: "YOUR_AUTH_TOKEN",
  baseURL: "YOUR_DEPLOYMENT_URL/v1",
});

const reply = await openai.chat.completions.create({
  model: "gpt-4",
  messages: [
    { role: "user", content: "Hello, who are you?" },
  ],
  stream: true,
});

const img = await openai.images.generate({
  prompt: "A painting of cat with a hat",
});
```

**Comment by PeronGH** [comment]
Also, I've developed an alternative front-end which is meant to be used the `webapi`. You can find details on how it interacts with the `webapi` [here](https://github.com/PeronGH/sydney_webui/blob/main/lib/services/sydney_service.dart).

**Comment by QiranYC** [comment]
THX, but I tried the api with python, and it was always responsing with code 500 as I coded as following:

cookie_path = pathlib.Path('cookies.json')
cookies = None
if cookie_path.exists():
    cookies = json.loads(cookie_path.read_text(encoding='utf-8'))
                    
headers = {
    "Content-Type": "application/json",
}

body = {
    "prompt": "",
    "context": "Hello, this is Bing.",
    "conversation": "CreateConversationResponse",
    "cookies": str(cookies),
    "noSearch": False,
    "conversationStyle": "Creative",
    "locale": "zh-CN",
    "gpt4turbo": True
}

response = requests.post("http://localhost:8080/chat/stream", headers=headers, json=body, stream=True)

**Comment by PeronGH** [comment]
Hi, there are several issues with how you call the API. First, the cookies should be obtained using `document.cookie` on the official website. Second, the `conversation` field should not be a string, but an object, whose structure is `CreateConversationResponse`, which is returned by `/conversation/new`. But the better solution is just to omit the `conversation` field, because it will be created automatically if omitted.

**Comment by QiranYC** [comment]
I've tried with postman:

{
    "prompt": "",
    "context": "Hello, this is Bing.",
    "noSearch": false,
    "conversationStyle": "Creative",
    "locale": "zh-CN",
    "gpt4turbo": true
}

And the response was as following:

error creating conversation: unexpected end of JSON input

**Comment by PeronGH** [comment]
Hi, the issue you encountered may be caused by missing cookies. Ensure that you have passed `DEFAULT_COOKIES` env to `webapi` or you may provide your own cookies in the payload. If you are in China, please make sure you have correctly configured the proxy. Also, the `prompt` must not be empty, and the `context` should follow internal template of Microsoft Copilot to perform prompt injection.

Here is an example cURL command to use the API:
```bash
curl -X POST "$BASE_URL/chat/stream" -d '{"prompt":"Who are you?","context":"None","cookies":"YOUR_COOKIES_HERE"}'

```

**Comment by QiranYC** [comment]
THX, can I provide cookies as this:

cookie_path = pathlib.Path('cookies.json')
cookies = None
if cookie_path.exists():
cookies = json.loads(cookie_path.read_text(encoding='utf-8'))

**Comment by PeronGH** [comment]
> THX, can I provide cookies as this:
> 
> cookie_path = pathlib.Path('cookies.json') cookies = None if cookie_path.exists(): cookies = json.loads(cookie_path.read_text(encoding='utf-8'))

No, you can't. You should go to [official website](https://www.bing.com/chat?q=Bing+AI&FORM=hpcodx), open the browser console, type `document.cookie`, and copy the result string.

**Comment by QiranYC** [comment]
So it's different from the program:

Put your cookies.json in the same folder as the executable file:
        Install the Cookie-Editor extension for [Chrome](https://chrome.google.com/webstore/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/cookie-editor/)
        Go to bing.com
        Open the extension
        Grant permission for All sites
        Click Export on the bottom right, then Export as JSON (This saves your cookies to clipboard)
        Paste your cookies into a file cookies.json, created in the same directory as the executable file.
        Note: make sure you can use the web chat before exporting the cookie.
    Run the program.

**Comment by PeronGH** [comment]
Yes, it is different from other parts of the program.

**Comment by QiranYC** [comment]
THX, you helped a lot
