### ISSUE TITLE
event: error data: "failed to get reader: received close frame: status = StatusNormalClosure and reason = \"\""

### ISSUE THREAD

**Issue by QiranYC** [juzeon/SydneyQt#158]
当上下文的tokens达到8k左右时报错

**Comment by PeronGH** [comment]
This issue might be related to Microsoft's limit on context length. It is caused by early termination of WebSocket connection from Microsoft's server. The solution is yet to be discovered.

**Comment by QiranYC** [comment]
https://github.com/Hansimov/bing-chat-api
