### ISSUE TITLE
[BUG] Cannot connect to host 

### ISSUE THREAD

**Issue by SamsuWei** [juzeon/SydneyQt#159]
Please help me with the following problem: Cannot connect to host hello-world-long-bird-0f21.bydymainit.workers.dev:443 ssl:default [The semaphore timeout has been exceeded]. My domain was entered without http prefixes, etc., what could be the problem? it is possible that the domain was created incorrectly, but it is unlikely... help please. (this is Qt 1 if anything)

**Comment by juzeon** [comment]
Please set up a usable proxy.
