### ISSUE TITLE
decode error

### ISSUE THREAD

**Issue by QiranYC** [juzeon/SydneyQt#160]
event: message
data: " <<<å¥"
event: message
data: " \u003c\u003c\u003c句"
event: message
data: "å­
event: message
data: "子"
event: message
data: "ç»æ
event: message
data: "结束"
event: message
data: "ä¸"
event: message
data: "专"
event: message
data: "ç¨"
event: message
data: "用"
event: message
data: "æ "
event: message
data: "标"
event: message
data: "è®°"
event: message
data: "记"
event: message
data: ">>"
event: message
data: "\u003e\u003e"
event: message
data: ">"
"
event: message
data: "\u003e\"\n"

**Comment by PeronGH** [comment]
Firstly please make sure you are using UTF-8 encoding. Some libraries may implement some auto detect mechanisms which may recognize it as other encoding. If the issue persists after forcing UTF-8 encoding, please provide steps to replicate the bug.
