### ISSUE TITLE
[FEATURE] CLI Version

### ISSUE THREAD

**Issue by marez-janati** [juzeon/SydneyQt#161]
i want a way to access the program and interract with it without a gui meaning a way to include it in my python automation
wails wouldn't install or work (i looked for all documentations) so i couldn't change the source code myself then build it 
i don't want to use the api since i didn't quite understand it instruction not so clear for me 

### Checks

- [ ] I confirm that I have searched existing issues and couldn't find a similar proposal.
- [x] I have read the documentation and test the software carefully and confirmed that this is not an existing feature.

**Comment by PeronGH** [comment]
CLI version is definitely possible and not difficult to develop as the foundation is already built. But I still think you should try out the API first. You can just use it with OpenAI SDK, which is very easy to get started with.

You can find more information [here](https://github.com/openai/openai-python), and don't forget to set `base_url` to the URL of `webapi` server.

**Comment by juzeon** [comment]
Not planning on a cli for now. Can discuss more.

**Comment by ikhwanperwira** [comment]
I need same, even I expect I those binary files can be accessed from CLI terminal
