### ISSUE TITLE
[BUG] 提示词下拉框宽度不恒定

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#162]
提示词的标题的长度是有区别的。

现在点了提示词选择框之后，开始会出现一个下拉框，使用某种长度。
如果这时候我开始用鼠标滚轮滑动选择，那么这里的提示词标题长度的变化会影响到下拉框的宽度。

从表现上，就是突然变长或者突然变短，向下或者向上都会触发。

使用上这样还是有点奇怪的。

**Comment by juzeon** [comment]
这个是UI库的问题，应该就是这么设计的。
