### ISSUE TITLE
[BUG] 部分内容在Rich text的渲染中会消失（Content disappears in the Rich text rendering）

### ISSUE THREAD

**Issue by NostalgiaGit** [juzeon/SydneyQt#163]
### Checks

- [√] I confirm that I have searched existing issues and couldn't find a similar bug.
- [√] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

I‘ve noticed that certain elements disappear in the rendered results within the Rich text, including Ordered numbers, Unordered signs, Blank lines and Content in <> symbols. Details are described below.

目前使用中发现以下几种内容会消失：

1. 序号。就比如像我现在这种格式的，`1. Context`（正文和序号之间有空格），在Rich text的渲染中那个序号1会消失。
2. 引导列表的其他符号。比如`-`或`+`这种，`- Context`（正文和序号之间有空格），在Rich text中也没有正确作为列表显示。

以上两点问题应该都出在那个空格上，不过一般Rich text的语法应该是支持空格的吧？

4. 空行。Rich text中没有显示空行。不过这个可能算个小问题，它实际是有空行的，如果把Rich text中的文本复制粘贴出来，该存在空行的地方是有空行的，只是它没有显示在Rich text里。（而上述那些序号则是真的没有，复制粘贴出来也没有）
5. 写在`<>`这种符号内的文字也会消失。不过我不确定这算不算bug，可能大部分Rich text的语法本来就是这样。

### Screenshots

上述内容在Plain Text和Rich Text中的对比如下，比较直观。
Plain text：
![image](https://github.com/juzeon/SydneyQt/assets/132838751/ed3dfa23-bd6f-4366-b9e6-6b1c5d85edbf)
Rich text：
![image](https://github.com/juzeon/SydneyQt/assets/132838751/17e600ac-f983-42a0-acc9-65fe752e5388)

### Desktop (please complete the following information):
 - OS and Version: [Windows 10]
 - SydneyQt Version: [v2.2.3]

**Comment by juzeon** [comment]
列表应该是bug。`<https://xxxx>`这种语法是markdown里面的超链接，按理来说如果是html代码的话应该包裹在代码块中。想想这地方怎么改。
