### ISSUE TITLE
[BUG] 2.X版本的字体是否被加粗过

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#164]
看2.0的字体，总感觉文字都特别拥挤，有点写字模糊不清的味道。

看图吧。

![image](https://github.com/juzeon/SydneyQt/assets/3251548/33362aad-69fb-4bfd-a40a-996316c439f3)

**Comment by juzeon** [comment]
内置了苹果字体的缘故（苹方+SF Pro Display）。可以在设置里改字体。
