### ISSUE TITLE
[BUG] 现在的标题生成有头重脚轻问题

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#165]
这里的头重脚轻的意思，是说生成的标题过于靠近context最开始的内容，而很少考虑之后的内容。

直接的表现，就是很容易将提示词的内容给总结出来，而不是将我的提问和bing的回答给总结了。

**Comment by juzeon** [comment]
给一点例子和完整context。

**Comment by riverai** [comment]
> 给一点例子和完整context。

看看这两个。先看下截图，自动生成的标题。
![image](https://github.com/juzeon/SydneyQt/assets/3251548/9eea6acd-bbbd-4ba1-9cae-1b3f34aff921)


然后看两个内容文本。
[内容1标题为学习英语语法.md](https://github.com/juzeon/SydneyQt/files/13726141/1.md)
[内容2标题为英语语法指导.md](https://github.com/juzeon/SydneyQt/files/13726142/2.md)

**Comment by juzeon** [comment]
图上看是正常行为。生成标题只在第一轮对话结束之后生成一次，不会考虑之后的对话。

ChatGPT网页版等实际上都是这么设计的。

**Comment by riverai** [comment]
> 图上看是正常行为。生成标题只在第一轮对话结束之后生成一次，不会考虑之后的对话。
> 
> ChatGPT网页版等实际上都是这么设计的。

不要将提示词一起发送过去就好了。

**Comment by juzeon** [comment]
将或不将additional_instructions发过去的话，实际上也没什么影响。因为Bing还内置了一大段提示词，会prepend到每一次的模型输入中。所以如果提示词对总结有影响的话，前面那一大段应该影响更大。

**Comment by riverai** [comment]
> 将或不将additional_instructions发过去的话，实际上也没什么影响。因为Bing还内置了一大段提示词，会prepend到每一次的模型输入中。所以如果提示词对总结有影响的话，前面那一大段应该影响更大。

有影响的。我还没见过bing总结出系统提示词，反而见过不少次在自己的提示词很长的时候，总结成了用户提示词。
