### ISSUE TITLE
[BUG] Error: unexpected end of JSON input

### ISSUE THREAD

**Issue by marez-janati** [juzeon/SydneyQt#167]
![2023-12-20 12_48_30-aimessenger - 20 65 200 119_3389 - Remote Desktop Connection](https://github.com/juzeon/SydneyQt/assets/109346761/9bc3d644-2b0f-45e6-ae6d-3f04869e33f5)
### Checks

- [ ] I confirm that I have searched existing issues and couldn't find a similar bug.
- [ ] I have read the documentation carefully and it couldn't resolved my problem.

### Desktop (please complete the following information):
 - OS and Version: [e.g. Windows 10]
 - SydneyQt Version: [e.g. v2.2.2]

**Comment by juzeon** [comment]
Please delete your `config.json` and try again.

**Comment by marez-janati** [comment]
yes it worked fine thank you !
(also if you think you can help me ,,,  i want a simple way to interact with the program without a gui 
,if the api is for that then m sorry i didn't quit understand how to use it , for example a good solution for a bigginer like me would be writing a json file containing the prompt and conversation + image path , then run a command that will get the response or something simple like that )
thank you again

**Comment by marez-janati** [comment]
yes it worked fine thank you !

**Comment by marez-janati** [comment]
(also if you think you can help me ,,, i want a simple way to interact with the program without a gui
,if the api is for that then m sorry i didn't quit understand how to use it , for example a good solution for a bigginer like me would be writing a json file containing the prompt and conversation + image path , then run a command that will get the response or something simple like that )
thank you again

**Comment by PeronGH** [comment]
> (also if you think you can help me ,,, i want a simple way to interact with the program without a gui ,if the api is for that then m sorry i didn't quit understand how to use it , for example a good solution for a bigginer like me would be writing a json file containing the prompt and conversation + image path , then run a command that will get the response or something simple like that ) thank you again

Actually the Web API is just as simple as what you've described. You just send the JSON to the server, which includes `prompt`, `context` and `imageUrl`, and the server will respond with a stream of text generated by Bing. Maybe you can send the documentation along with your requirement to Bing, and perhaps it can tell you how to make such web requests.
