### ISSUE TITLE
希望作者可以使Rich界面显示函数等数学公式，可以类似网页版的bing,谢谢！

### ISSUE THREAD

**Issue by xyz1108** [juzeon/SydneyQt#168]
软件里生成的表达方式
![image](https://github.com/juzeon/SydneyQt/assets/105235659/a6f9ce34-2785-4dec-9b97-93f855b44c93)
并且有可能生成下面的表达方式
![image](https://github.com/juzeon/SydneyQt/assets/105235659/52f0bc0c-a2f3-4ae6-9d53-6dd8be156f70)

网页版bing的表达方式
![image](https://github.com/juzeon/SydneyQt/assets/105235659/3a0ac66a-0b93-4858-ae21-a804d786b92e)
![image](https://github.com/juzeon/SydneyQt/assets/105235659/53ce2c04-7e14-44bf-a222-0f37ef26ac33)

**Comment by juzeon** [comment]
提供一下截图中的完整chat context文本。

**Comment by xyz1108** [comment]
请表达一下绝对值函数。


重复一遍
- 绝对值函数：$$f(x) = |x| = \begin{cases} -x, & x < 0 \\ x, & x \geq 0 \end{cases}$$
- 符号函数：$$g(x) = \text{sgn}(x) = \begin{cases} -1, & x < 0 \\ 0, & x = 0 \\ 1, & x > 0 \end{cases}$$
- 阶梯函数：$$h(x) = \lfloor x \rfloor = \max \{n \in \mathbb{Z} : n \leq x \}$$

**Comment by xyz1108** [comment]
![image](https://github.com/juzeon/SydneyQt/assets/105235659/2abf6534-e469-4f9e-ae0a-d12fc6635ccd)
![image](https://github.com/juzeon/SydneyQt/assets/105235659/9ea21233-3283-4451-be29-0d16278517ce)
完整chat context文本：你可以详细介绍阶梯函数吗？
希望作者可以修改为网页版形式，方便更好地理解。

**Comment by juzeon** [comment]
![圖片](https://github.com/juzeon/SydneyQt/assets/12206799/d0efab81-da11-4e07-bb6f-7c18e83376fb)

下个版本发布。
