### ISSUE TITLE
[BUG] 似乎图片生成功能依赖搜索功能,希望可以同时启用关闭搜索和生成图像

### ISSUE THREAD

**Issue by Cis-Evo** [juzeon/SydneyQt#169]
经测试,一旦开启关闭搜索,无论是否对规则进行改动,都会导致AI无法提交 #generative_image 请求.
关闭则正常,但开启似乎会影响注入规则对AI的洗脑程度.
即便在规则中注明如何通过[assistant](#generative_image)生成图片,依然如此,具体调用方式不明

**Comment by juzeon** [comment]
Have to blame Bing for this.
