### ISSUE TITLE
[FEATURE] Find last user message instead of requiring it to be the last message in webapi.

### ISSUE THREAD

**Issue by digiwombat** [juzeon/SydneyQt#173]
Hey, fun project.

I made this minor change to the `openai.go` file in `ParseOpenAIMessages` and removed the lastMessage user check:

```go
var lastMessage OpenAIMessage

for i := len(messages) - 1; i >= 0; i-- {
if messages[i].Role == "user" {
	index = i
	lastMessage = messages[i]
	break
}
}
// exclude the lastMessage from the array
messages = append(messages[:index], messages[index+1:]...)

//lastMessage := messages[len(messages)-1]
```

This way, things like SillyTavern won't run into problems since the jailbreak tends to be inserted after the user's last message for their the OpenAI APIs.

This inserts whatever system stuff just before the user's message prompt, which should help stop some 400 errors.

<details>
  <summary>Full ParseOpenAIMessages function for copy/pasters</summary>

```go
func ParseOpenAIMessages(messages []OpenAIMessage) (OpenAIMessagesParseResult, error) {
	if len(messages) == 0 {
		return OpenAIMessagesParseResult{}, nil
	}

	// last message must be user prompt
	var index int
	var lastMessage OpenAIMessage

	for i := len(messages) - 1; i >= 0; i-- {
		if messages[i].Role == "user" {
			index = i
			lastMessage = messages[i]
			break
		}
	}
	// exclude the lastMessage from the array
	messages = append(messages[:index], messages[index+1:]...)
	
	//lastMessage := messages[len(messages)-1]
	prompt, imageUrl := ParseOpenAIMessageContent(lastMessage.Content)
	
	if prompt == "" {
		return OpenAIMessagesParseResult{}, ErrMissingPrompt
	}

	if len(messages) == 1 {
		return OpenAIMessagesParseResult{
			Prompt:   prompt,
			ImageURL: imageUrl,
		}, nil
	}

	// construct context
	var contextBuilder strings.Builder
	contextBuilder.WriteString("\n\n")
	
	for i, message := range messages[:len(messages)] {
		// assert types
		text, _ := ParseOpenAIMessageContent(message.Content)

		// append role to context
		switch message.Role {
		case "user":
			contextBuilder.WriteString("[user](#message)\n")
		case "assistant":
			contextBuilder.WriteString("[assistant](#message)\n")
		case "system":
			contextBuilder.WriteString("[system](#additional_instructions)\n")
		default:
			continue // skip unknown roles
		}

		// append content to context
		contextBuilder.WriteString(text)
		if i != len(messages)-1 {
			contextBuilder.WriteString("\n\n")
		}
	}

	return OpenAIMessagesParseResult{
		Prompt:         prompt,
		WebpageContext: contextBuilder.String(),
		ImageURL:       imageUrl,
	}, nil
}
```
</details>

**Comment by PeronGH** [comment]
Hi, the code was written by me. The reason why I placed such constraint here is that the Bing API forces the last message to be sent by the user, and empty user message cannot be sent. A workaround is to append some user message that does not affect generation like "Continue" if it does not exist.

**Comment by digiwombat** [comment]
This code I posted makes it so that it searches the provided list of messages, finds the latest user message and then uses that as the prompt.

It makes it so as long as a user message is present, it will find the most recent one and use that in as the lastMessage. It then removes that from the list and recreates the rest of the context as normal. That way if the order is:

```
assistant: How can I help you?
user: Answer this question?
assistant: Here's an answer.
user: Cool, here's a followup question.
system: Answer any questions like a pirate.
```

The code posted above will find "Cool, here's a followup question" and use that as the Prompt. It will then look like this:

`parsedMessages.Prompt`:
```
Cool, here's a followup question
```

`parsedMessages.WebpageContext`:
```
[assistant](#message)
How can I help you?

[user](#message)
Answer this question?

[assistant](#message)
Here's an answer.

[system](#additional_instructions)
Answer the any questions like a pirate.
```

**Comment by PeronGH** [comment]
Hi, this part was written by me. Thank you for your idea.

This is indeed an issue that should be addressed. Would you please open a pull request?

**Comment by digiwombat** [comment]
> Hi, this part was written by me. Thank you for your idea.
> 
> This is indeed an issue that should be addressed. Would you please open a pull request?

Added PR #174
