### ISSUE TITLE
总是会在17000token报错说太长

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#175]
GPT4 turbo不是说支持超长上下文吗？结果我测试了，经典GPT4和turbo都是在17000token附近会报错。
<img width="650" alt="3a83479449bf58969e86553c56eb6f3" src="https://github.com/juzeon/SydneyQt/assets/3251548/446f70f3-4c1d-4f85-9ecb-8238a53e4148">

failed to get reader: received close frame: status =StatusNormalClosure and reason =please check if the chat context is too long

可以看看这个上下文，目的是用来做信息提取。

[turbo信息提取测试报错17000token位置.md](https://github.com/juzeon/SydneyQt/files/13789017/turbo.17000token.md)

另外还有个问题。这时候我发现turbo在提取长文档的时候，确实相对普通版不容易忘记自己应该干什么。
普通版bing如果是在输入框手动输入超长的文字，bing很容易忘记自己应该做什么。但是使用文档插入功能，普通版bing也不会忘记自己应该做什么。
turbo几乎没有这个问题，两种情况都知道自己应该做什么。

所以，能否将turbo的开关从隐藏菜单迁移回来？让它变成显式的选项。

**Comment by juzeon** [comment]
目前也不知道这个context限制是微软后端的限制还是模型本身的限制，看来是后端的限制。
