### ISSUE TITLE
[BUG] Error:json:cannot unmarshal arrat into Go value of type main.

### ISSUE THREAD

**Issue by SDU-Gary** [juzeon/SydneyQt#177]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

When I downloaded the executable, ran it once to generate config.json, copied the json from the browser's extension into the file and then ran it again, I got this error.

### To Reproduce
1. Download the 'SydneyQt-windows-amd64.exe'.
2. Run once and exit.
3. Copy json to the 'config.json'.
4. Run again,then See error.

### Screenshots
![屏幕截图 2023-12-29 213141](https://github.com/juzeon/SydneyQt/assets/118115956/a42a8bad-4460-43ae-a121-128ad250d8ab)

### Desktop
 - Windows 11
 - v2.2.4

**Comment by juzeon** [comment]
You need to paste your cookies into cookies.json rather than config.json. It is up to you to create the cookies.json file.

**Comment by SDU-Gary** [comment]
Oh I'm SB.
