### ISSUE TITLE
[BUG] 闪退问题

### ISSUE THREAD

**Issue by SDU-Gary** [juzeon/SydneyQt#178]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

程序运行后会遇到闪退问题,目前遇到三种会导致闪退的情况
1.上传文件或图片后会闪退,闪退后可以立刻重新打开,但文件和图片均未成功上传.
2.对电脑任务栏的Qt图标连续点击会闪退,闪退后可以立刻重新打开.
3.经过一段时间后(具体时间没有准确测试),单击任务栏图标便会闪退,这种闪退后不能重新打开,产生下图错误

以上三种情况直接运行执行文件和通过快捷方式运行都会产生

### Screenshots

![屏幕截图 2023-12-30 123848](https://github.com/juzeon/SydneyQt/assets/118115956/4f54129a-79ab-49fd-8e6d-abfe387bfe64)

### Desktop (please complete the following information):
 - Windows 11
 - SydneyQt v2.2.4

**Comment by juzeon** [comment]
上传图片或文件是否曾经至少成功上传过一次？

**Comment by SDU-Gary** [comment]
新版本的没有成功上传过,旧版本记不太清了,但是有过上传文件成功但是超token

**Comment by juzeon** [comment]
I'm closing this as it seems not reproducible.
