### ISSUE TITLE
[FEATURE] 是否可以在图片生成后直接下载原尺寸的图片？（Downloading Images with the Original Size from the App）

### ISSUE THREAD

**Issue by NostalgiaGit** [juzeon/SydneyQt#181]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar proposal.
- [x] I have read the documentation and test the software carefully and confirmed that this is not an existing feature.

### Is your feature request related to a problem? Please describe.

在Edge侧边栏或网页使用Bing生成图片时，默认会显示缩略小图，如果直接右键点击保存图片，默认保存的也是该缩略小图。但如果点击图片进入Image Creator的页面，则会看到图片原尺寸是1024x1024的，在这里下载也会下载到大尺寸的图片。

而目前SydneyQt App中，生成图片后点击下载，默认下载的也是那个缩略小图的尺寸。请问是否方便把它做成可以直接下载原尺寸大图的功能呢？

**Comment by PeronGH** [comment]
I don't use the desktop version, but from what I learned when developing the alternative front end, It is quite easy to download the image of original size. Just remove the queries (anything following `?`) from the image url and you can download the original image.

**Comment by NostalgiaGit** [comment]
Thanks, mate. It works on the website. However, the download URL in the desktop app cannot be manually modified. Hopefully, this feature could be added later.
