### ISSUE TITLE
Embed Feature

### ISSUE THREAD

**Issue by ThePatriotsXOF** [juzeon/SydneyQt#182]
Hello, I like this client very much however the only issue I'm having is that when bing gives embedded messages, it redirects me to a localhost link instead of a url.
example when I click and embed like this:
![SydneyQt-windows-amd64_5jTLgLXTJ4](https://github.com/juzeon/SydneyQt/assets/150899804/73458132-212f-40df-ae08-71791435ab66)

It redirects through here:
![librewolf_bezt04JLhv](https://github.com/juzeon/SydneyQt/assets/150899804/e45dafe6-c133-4ad3-83fa-3fcdfce02b11)

The other problems are the reference numbers, It dosent embed like the native bing chat on the websites. (e.g [^1] )
Example of the screenshot:

![SydneyQt-windows-amd64_9tRkc27MPG](https://github.com/juzeon/SydneyQt/assets/150899804/0b50f018-1db6-429a-a8ae-91d10a1bec41)

Overall good client and I hope this gets ported on android too someday.

**Comment by juzeon** [comment]
Would you please share the complete chat context that has the link issue?

**Comment by ThePatriotsXOF** [comment]
the embeds I mean like the blue text where it redirects the link

**Comment by ThePatriotsXOF** [comment]
Here is more proper context


https://github.com/juzeon/SydneyQt/assets/150899804/c1919dd9-80b9-42ad-ab38-205e58d57ca8

**Comment by juzeon** [comment]
Thanks. But I would need the full chat context as plain text. You need to switch to the plain tab and copy & paste it here, wrapped in code block syntax. Or use pastebin etc.

**Comment by ThePatriotsXOF** [comment]
Hello, I accidentally deleted the similar one from the video and recreated a similar prompt like in the video, here are the plain text
https://pastebin.com/MD8uha5B
