### ISSUE TITLE
[BUG] Didn't see anything when run app. 

### ISSUE THREAD

**Issue by orcbolg3612** [juzeon/SydneyQt#184]
I didn't see anything when run app, i am using fedora 39.  
![image](https://github.com/juzeon/SydneyQt/assets/154581201/a9561736-0cda-4efd-84d7-acebc0fd3a4e)

**Comment by orcbolg3612** [comment]
My json:

[
    {
        "domain": ".bing.com",
        "expirationDate": 1739451211.92749,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SRCHUSR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "DOB=20240107&T=1704891078000&TPC=1704891211000&POEX=W"
    },
    {
        "domain": ".bing.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "_Rwho",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "u=d"
    },
    {
        "domain": "www.bing.com",
        "expirationDate": 1704893781,
        "hostOnly": true,
        "httpOnly": false,
        "name": "ai_session",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "Mq+ETTVugZqha27M3GBF23|1704891081318|1704891981161"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1739451984.055204,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SRCHHPGUSR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "SRCHLANG=en&PV=6.6.8&WTS=63840487878&HV=1704891984&IG=A55315A4637B409F80FBCB4FA2CAB548&BRW=XW&BRH=M&CW=1920&CH=942&SCW=1920&SCH=942&DPR=1.0&UTC=420&DM=1&PRVCW=1920&PRVCH=942&CIBV=1.1445.5"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1720615880.011758,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ANON",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "A=43AB5059ED4C7E24C6DB14F8FFFFFFFF&E=1d43&W=1"
    },
    {
        "domain": "www.bing.com",
        "expirationDate": 1736427981.06493,
        "hostOnly": true,
        "httpOnly": false,
        "name": "MicrosoftApplicationsTelemetryDeviceId",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "340310c0-c032-42ee-869b-5898ab378410"
    },
    {
        "domain": ".bing.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_SS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "SID=01D8826D8E706EE51F5191928FB06F71&R=0&RB=0&GB=0&RG=0&RP=0"
    },
    {
        "domain": ".bing.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "ipv6",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "hit=1704894678991&t=4"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1706100680.011924,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_U",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1yiJsmZ1OYMskxxQYRJZuCYOcA9TbK_0RbjNzlTXnutICxRcSYzYRWMntgW_0B6m5W82yPI9NcFOh7F3cpNt0PAF4kLZlDZB6VZEnazOeqbNRIxB69JUa2PV8of_sVXvOchUp41VunLFKoOsujsswAws_26yN14qdAnYkhed4PsYvDsTuXMs61Lp1kqlfkrdRflcLLJXHY2ehwBFLypbx1g"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1739185617.199417,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SRCHD",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AF=codexx"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1739451080.011831,
        "hostOnly": false,
        "httpOnly": false,
        "name": "PPLState",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1722196280.011804,
        "hostOnly": false,
        "httpOnly": false,
        "name": "NAP",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "V=1.9&E=1ce9&C=HEPuFjqXvbwywW2S1W-pxfamlHbVLSZPznuqcP7nhC5D1_3jlEYAUg&W=1"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1739451981.438111,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_RwBf",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "r=0&ilt=2&ihpd=1&ispd=0&rc=0&rb=0&gb=0&rg=0&pc=0&mtu=0&rbb=0.0&g=0&cid=&clo=0&v=9&l=2024-01-10T08:00:00.0000000Z&lft=0001-01-01T00:00:00.0000000&aof=0&ard=0001-01-01T00:00:00.0000000&rwdbt=0001-01-01T16:00:00.0000000-08:00&o=0&p=MSAAUTOENROLL&c=MR000T&t=5257&s=2024-01-01T07:38:55.5850732+00:00&ts=2024-01-10T13:06:21.2923429+00:00&rwred=0&wls=2&wlb=0&wle=0&ccp=0&lka=0&lkt=0&aad=0&TH=&mta=0&e=JalJRh028-iaRvXwWc9IolMYOx-ftxh2UbDg3dKr1gs0aIG8-m0KRDmqFC6W-JByQ_EmfVMlmMgsAnS5jW7jxQ&A=43AB5059ED4C7E24C6DB14F8FFFFFFFF"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1739451980.914478,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_UR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "QS=0&TQS=0"
    },
    {
        "domain": ".bing.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "_EDGE_S",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "SID=17EEE6F81B5C69C703E6F5071A4E680B"
    },
    {
        "domain": ".bing.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "_C_ETH",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": "www.bing.com",
        "expirationDate": 1738587945.927065,
        "hostOnly": true,
        "httpOnly": true,
        "name": "MUIDB",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "26B5C6A2A3106CDC06FFD55DA2D06DA0"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1739451981.007081,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_HPVN",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "CS=eyJQbiI6eyJDbiI6MSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiUCJ9LCJTYyI6eyJDbiI6MSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiSCJ9LCJReiI6eyJDbiI6MSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiVCJ9LCJBcCI6dHJ1ZSwiTXV0ZSI6dHJ1ZSwiTGFkIjoiMjAyNC0wMS0xMFQwMDowMDowMFoiLCJJb3RkIjowLCJHd2IiOjAsIlRucyI6MCwiRGZ0IjpudWxsLCJNdnMiOjAsIkZsdCI6MCwiSW1wIjoxMywiVG9ibiI6MH0="
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1739451080.011854,
        "hostOnly": false,
        "httpOnly": true,
        "name": "KievRPSSecAuth",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "FAByBBRaTOJILtFsMkpLVWSG6AN6C/svRwNmAAAEgAAACO2VwplUHQmQMAT+N2SvkDr+69iUiG4PzsCqy32hVA9y6k3Q4qnJIEfOGoDmbLWJLZbL/MpJho37ynAzcsM8vryY2k3PXYJHJzGAZJ492uPCX6t3FPYiUYguMvtJ0vFsVcMXzCHB4qXEYWbzYWXPkVWFgVPi7fb5Oje98e935hALYOmjSr0wiYob2e3iNNI0jzNhaIwcDPggDwn0xLswE5+kKK/lj1PjxxiJDAshOrr0a4MNwsuxIaTXLYXNjg5NkSyPeI38EFfgRhOZYfB9gR4k57Lj7Rag1RcAPZ5/erOg++9Pl+5NBVD8/6g52grMZ4CGaE0pDYU44Mhjoewzakmgyo/2aC84gEFKJGOaQ/1/Cjh8zGXMVC8uCisYQ4lyL02S3iwwVXMZ64sKu4OVo0yZnWIa064OvGEgys3EcZHnhKcsOMo5QMM6UgLfB/8Oc5ZmISbSfqfFkuNqU9AYc6R6R10FDbDuLOHcv0digbhVNkBmWxvdDBugKsPxoDEhvGir2kMoXDoPPVyNoccuSawW/+XNpjvOFN77nZeFxK7NdUiSv3JAfBNlShGqguedd39nyfbmQWNp4NLfV0xgvimbQ+6DgId8kQArUIoadvEEgMF4UFm4+nS6MHXObvb/s66bdvW8l/neBoVb+mV/OE9+aIm5ZDOg3CyyIoXwOclnDp5r79XeyAcDeU6zvVRaRUvenN6995WyWPwe+H4a32dEQKeOLlE1lVbBJGzMYFKEyj7iKwZb80yM548WjT8xx29uPuFu5MdQCnApPI4sr1ufuQmZ8DoI2jIrRt7aznhQGnmW/JZYzQfAuggsc3pLdkozPHTgfjp9y7ttA4hTj1w/+bQdKBGCXh9Fv4fP6Ys+Nj+GgDfN4hA61P6NXNkQcaysCc0ge1OobdTZEVGQTW64xELR5CtxsX0YUmDl0wUnWHV4F235KdQl2PPOetKA6htCeUkFqzBUOnkjs93aOcsiv58BRloG1pqhI92UQ/w+pRNfGxhWKcPjh/efIqt3hXNuDjhyC8q9VF2aePDzEkS758RTsW8oT578wWGdzttHx6Tvv3Vd4yLwCO+SPg/x4LZ2JvYqL9wcPAvtXxYBz3jm+JDef7KSfJY8BPYVHY7SIa0G5ABS6eIb4QgrT4ltlzU7DCcBp6VgutyOcZhm7wCM0s85lSovvpwPv9iyTUdymZ35Uotgdl9OOEgSXTzEdJYOGKZKcdUhRQO7tWnWb78IrpJ9akh1tAr05/W7EF0Wzw6daOLr34ubVk8Umwx/byRS3aIciSHOG7vclLNNWSUDI5gDmma/XN1oG4zUpKkhGkyTOA6RQrYD4RK5XrRZYYozDi8AF+h0dgMwZcLnb4Yc0K2f3KxhzXXVJqAAWW4+INnQUEAFowSG9SMGUcPa8TdjQdAknhOgIz6hQT1/PbW+WHiw7HIBpRgMFACOL0yY+14+2ma2PfE4cK7vcTz++w=="
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1738321617.199217,
        "hostOnly": false,
        "httpOnly": false,
        "name": "MUID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "26B5C6A2A3106CDC06FFD55DA2D06DA0"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1739185617.199447,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SRCHUID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "V=2&GUID=FA30B5CA3D584006885FAA24B0A219C2&dmnchg=1"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1706100690.413629,
        "hostOnly": false,
        "httpOnly": true,
        "name": "WLID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "GBlgyG3UaUfzrZ+HxvVt6RYMf1wUGHHl6dNl1Ub2Sk0IEGWNH45Jx3RTli2aTjZoTrE2PXG2qjaxYmmiYfi1O+hXx0L9wk0IFvCVhRth9uo="
    },
    {
        "domain": ".bing.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "WLS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "C=357a2b787be4d119&N=3612"
    }
]

**Comment by lindgrenar** [comment]
Try running it from terminal. I almost guarantee that you are missing `libwebkit2gtk-4.0`

`sudo dnf install webkit2gtk4.0` would solve it.

And I'd probably remove that cookie you shared...

**Comment by orcbolg3612** [comment]
It works, thanks.
