### ISSUE TITLE
[BUG]画库洛米会报错

### ISSUE THREAD

**Issue by ghost** [juzeon/SydneyQt#185]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### To Reproduce
1. Go to '...'  在对话框输入画一个库洛米
2. Click on '....' 接着会转圈圈，然后报错，不管是gpt4 turbo还是普通模式都会报错，但是聊天是没有问题的

### Screenshots
![企业微信截图_20240111140238](https://github.com/juzeon/SydneyQt/assets/138294823/754fb25d-f805-423f-999e-546546a9d66d)
![企业微信截图_20240111140344](https://github.com/juzeon/SydneyQt/assets/138294823/466fcb89-9419-4d26-8aba-0119b14e2653)
![企业微信截图_20240111140435](https://github.com/juzeon/SydneyQt/assets/138294823/35ca7d38-f480-481f-a205-ceaeeaa74515)

### Desktop (please complete the following information):
 - OS and Version: [e.g. Windows 10] windows11
 - SydneyQt Version: [e.g. v2.2.2]  2.2.5

**Comment by ghost** [comment]
上传图片也会报错
![企业微信截图_20240111141304](https://github.com/juzeon/SydneyQt/assets/138294823/ac438718-5a6e-4e05-a473-d732f0beb162)

**Comment by juzeon** [comment]
关键词被Bing审查了，换别的吧。

上传图片我这没问题，可能是图片太大了。
