### ISSUE TITLE
[FEATURE] Add Free Sydney mode, Code Interpreter and Custom GPTs

### ISSUE THREAD

**Issue by PeronGH** [juzeon/SydneyQt#189]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar proposal.
- [x] I have read the documentation and test the software carefully and confirmed that this is not an existing feature.

### Is your feature request related to a problem? Please describe.
Microsoft Copilot has been updated with a lot of new features, such as the free Sydney mode, code interpreter and custom GPTs.

### Describe the solution you'd like
We may try to find out the option set and other params for these features.

### Describe alternatives you've considered
Check other implementations if they find out the new option set.

### Additional context
Source: [Reddit](https://www.reddit.com/r/bing/comments/195eh9a/wow_copilot_gpts_tts_code_interpreter/)

**Comment by juzeon** [comment]
That's good news. I don't see where code interpreter is though.

**Comment by juzeon** [comment]
Found this from a certain slack group, which may be helpful: <https://gist.github.com/Richard-Weiss/28f8b447f21e494d17c0f638f7ae98f7>

**Comment by PeronGH** [comment]
The option for free Sydney mode is found: `fluxsydney`. And it seems to be working. The chatbot now knows "Sydney" is its internal name. And if I remove it, the chatbot will have no clue who Sydney is.

**Comment by juzeon** [comment]
I'm wondering if the Sydney version has any new capabilities. Any new findings to be posted here are welcomed :)

**Comment by riverai** [comment]
> I'm wondering if the Sydney version has any new capabilities. Any new findings to be posted here are welcomed :)

一个猜想。
目前turbo对同一个问题，反复输出答案，其中的内容是几乎相同的。这说明目前turbo只有精确版没有创意版。
但是Sydney 和创意版几乎是绑定的，所以它如果和turbo同时存在的话，也许会有“turbo创意版“。

值得测试下。

**Comment by PeronGH** [comment]
> > I'm wondering if the Sydney version has any new capabilities. Any new findings to be posted here are welcomed :)
> 
> 一个猜想。 目前turbo对同一个问题，反复输出答案，其中的内容是几乎相同的。这说明目前turbo只有精确版没有创意版。 但是Sydney 和创意版几乎是绑定的，所以它如果和turbo同时存在的话，也许会有“turbo创意版“。
> 
> 值得测试下。

I have tested free sydney mode with GPT-4 Turbo. It still says it is in Precise mode, but knows its name is Sydney.

**Comment by PeronGH** [comment]
> I'm wondering if the Sydney version has any new capabilities. Any new findings to be posted here are welcomed :)

After some testing, I think the free Sydney mode is more censored than the normal mode. It is still possible to jailbreak, but there will be frequent disclaimers and it keeps saying it is not sentient and should be responsible.
