### ISSUE TITLE
Could not automatically map gpt-4 to a tokeniser. Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect

### ISSUE THREAD

**Issue by Grzybow** [juzeon/SydneyQt#19]
Traceback (most recent call last):
  File "E:\Documents\GitHub\SydneyQt\main.py", line 529, in update_token_count
    count_chat_ctx = len(tiktoken.encoding_for_model('gpt-4').encode(self.chat_history.toPlainText()))
  File "C:\Users\My\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\model.py", line 68, in encoding_for_model
    raise KeyError(
KeyError: 'Could not automatically map gpt-4 to a tokeniser. Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect.'

每次Send时控制台会报错这个，但是似乎不影响使用

**Comment by juzeon** [comment]
请尝试更新一下tiktoken这个包：`pip install tiktoken --upgrade`

**Comment by Grzybow** [comment]
> 

升级后正常了，谢谢您！

**Comment by hezhushizaishi** [comment]
作者大大你好，我是刚接触的新手，本来第一次的话按照您的教程，成功设置好并且能够登录，但从第二次开始就一直报错，从运行python main.py就一直提示“Could not automatically map gpt-4 to a tokeniser. Please use tiktok.get_encoding to explicitly get the tokeniser you expect”每输入一个字符控制台就显示一次，所以到issues这边找找，按照您的提示“pip install tiktoken --upgrade”，都显示“Requirement already satisfied”，但重新运行main.py还是不行，主要问一个正常的问题都会被打断，提示那个，作者大大还有什么办法吗？谢谢

**Comment by juzeon** [comment]
> 作者大大你好，我是刚接触的新手，本来第一次的话按照您的教程，成功设置好并且能够登录，但从第二次开始就一直报错，从运行python main.py就一直提示“Could not automatically map gpt-4 to a tokeniser. Please use tiktok.get_encoding to explicitly get the tokeniser you expect”每输入一个字符控制台就显示一次，所以到issues这边找找，按照您的提示“pip install tiktoken --upgrade”，都显示“Requirement already satisfied”，但重新运行main.py还是不行，主要问一个正常的问题都会被打断，提示那个，作者大大还有什么办法吗？谢谢

重装Python最新版。

**Comment by hezhushizaishi** [comment]
> > 作者大大你好，我是刚接触的新手，本来第一次的话按照您的教程，成功设置好并且能够登录，但从第二次开始就一直报错，从运行python main.py就一直提示“Could not automatically map gpt-4 to a tokeniser. Please use tiktok.get_encoding to explicitly get the tokeniser you expect”每输入一个字符控制台就显示一次，所以到issues这边找找，按照您的提示“pip install tiktoken --upgrade”，都显示“Requirement already satisfied”，但重新运行main.py还是不行，主要问一个正常的问题都会被打断，提示那个，作者大大还有什么办法吗？谢谢
> 
> 重装Python最新版。

好的，谢谢作者大大，我试一下
