### ISSUE TITLE
[Feature] Ability To Use Other Search Engines Than Bing

### ISSUE THREAD

**Issue by ThePatriotsXOF** [juzeon/SydneyQt#190]
If its possible can you add support for Baidu, Google, Duckduckgo, Yandex, Sogou, Ecosia, You, Startpage, Brave, etc. rather on being on bing by default?

**Comment by juzeon** [comment]
I would say not considering this at the mo. PRs are welcomed.

**Comment by PeronGH** [comment]
I don't think it would be easy though. The search feature is provided by Microsoft and is tightly built into the chatbot, which is not something we can control. Sophisticated workarounds may be possible, but they are sort of out of scope for this project.
