### ISSUE TITLE
[FEATURE] Merge GPT-4 Turbo and Precise Mode

### ISSUE THREAD

**Issue by PeronGH** [juzeon/SydneyQt#191]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar proposal.
- [x] I have read the documentation and test the software carefully and confirmed that this is not an existing feature.

### Is your feature request related to a problem? Please describe.
When GPT-4 Turbo is enabled, Sydney will be forced to use Precise mode, which makes GPT-4 Turbo conflict with the selected conversation mode.

### Describe the solution you'd like
We can have something like this:

```go
optionsSetMap: map[string][]string{
	"Creative": append(basicOptionsSet, "h3imaginative"),
	"Balanced": append(basicOptionsSet, "galileo"),
	"Precise":  append(basicOptionsSet, "h3precise", "dlgpt4t"),
}
```

And it may require some other changes in frontend and webapi.

**Comment by juzeon** [comment]
> When GPT-4 Turbo is enabled, Sydney will be forced to use Precise mode, which makes GPT-4 Turbo conflict with the selected conversation mode.

How's this discovered (and confirmed). Is this from the Bing website etc?

**Comment by PeronGH** [comment]
> How's this discovered (and confirmed). Is this from the Bing website etc?

You can ask Sydney "what's your mode".

**Comment by riverai** [comment]
I think we should wait a while. 
Bing will surely officially launch turbo , and will launch turbo-based creative.

**Comment by vitordelucca** [comment]
> > How's this discovered (and confirmed). Is this from the Bing website etc?
> 
> You can ask Sydney "what's your mode".

The model is not fully aware on which Tone it is. 

Btw, on Copilot Pro,  GPT4 Turbo only works on creative.... the toggle switch uses gpt4tmnc OptionSet...

But as of today, dlgpt4t stopped working...

**Comment by PeronGH** [comment]
> But as of today, dlgpt4t stopped working...

Mine is still working though. BTW, as you have Copilot Pro, would you please tell us more details about the option set? And it would be better if you can show us the initial message sent by client in websocket connection.

**Comment by PeronGH** [comment]
> But as of today, dlgpt4t stopped working...

`dlgpt4t` stopped working for me just now. And `gpt4tmnc` is not working either. I'm still experimenting with different option sets.

**Comment by vitordelucca** [comment]
> 
> Mine is still working though. BTW, as you have Copilot Pro, would you please tell us more details about the option set? And it would be better if you can show us the initial message sent by client in websocket connection.

> 
> `dlgpt4t` stopped working for me just now. And `gpt4tmnc` is not working either. I'm still experimenting with different option sets.

I don't have Copilot Pro, sadly. Just looked at the code, and the GPT4 Turbo switch enables gpt4tmnc... 
At first when I tried to use gpt4tmnc, it would just refuse the connection. But now, just like dlgpt4t, both have just no effect at all.

I guess they probably switched to another OptionSet...

**Comment by PeronGH** [comment]
According to the latest findings on GPT-4 Turbo, it is not limited to precise mode. It can also operate without being set to any specific mode. Therefore, this issue is no longer valid.
