### ISSUE TITLE
[BUG] 试图调用第三方Openai Api时再次出错

### ISSUE THREAD

**Issue by NostalgiaGit** [juzeon/SydneyQt#193]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

不好意思又是我 XD 。之前曾经报过一次无法调用api的错 (https://github.com/juzeon/SydneyQt/issues/142), 当时解决了，但今天发现又开始报错了。这次是在试图使用时弹出了一个错误窗口，上面提示：```error, status code: 403, message: invalid character '<' looking for beginning of value```.

和上次一样，这次也是有的三方api没问题，但有的就不行。包括上次问题已经解决了的那个中转api，这次又出问题了。我想这应该不是SydneyQt的问题，而是对方那边又做了什么更改导致的。不过因为手头好几个api都弹了这个错误，应该也算个普遍性问题，所以还是想看看作者这边是否有可能解决一下。十分感谢 XD 

### Desktop (please complete the following information):
 - OS and Version: [e.g. Windows 10]
 - SydneyQt Version: [e.g. v2.2.6]

**Comment by juzeon** [comment]
我这边没有办法复现

你在设置里面把Debug打开，然后触发一下报错，把最新的日志文件贴一下。

**Comment by NostalgiaGit** [comment]
谢谢，我刚才记录测试信息时居然也成功了一次，然后再试就又不行了，后来我研究了一下发现居然是网络问题，把代理关了就成功了。。。XD 但是我还是很疑惑，我还特意拿Chatgpt next web也试了一下，开着代理时在next web是可以正常使用这个api的，不知道为什么在SydneyQt会遇到网络问题（我是开tun模式的）。

这里还是贴一下log信息，看看作者是否有什么头绪XD。链接：https://pastebin.com/5zLkrU8r

另外我对log里的另一个信息有点疑问，从日志来看这里跟之前那个python程序一样，调用模型时有ShortModel和LongModel切换的设置，Threshold是3500，但以前那个python程序这里是可以自定义设置的，而新的SydneyQt没有，那这会导致上下文超过3500tokens时模式被自动切换成gpt-3.5-turbo-16k吗？

我简单拿一个4500tokens的长文档测试了一下，应该是没切换，从api站点那边的日志和模型实际表现来看，只要我要求它使用比如4-1106，那么即便超过3500tokens的长下文，模式也不会切换成3.5-16k，所以这个log里记录的是一个已经失效的无用信息吗？（本来想把长文对话的log也贴一下，但是日志里包含大量filter检测的信息，其中涉及一大堆敏感词，pastebin不让我粘 :sweat_smile:）

**Comment by juzeon** [comment]
返回的错误码是403，可能是所用的代理IP被第三方服务商禁止了？

v2是没有实现模型切换的，配置文件里那个是历史遗留问题，目的是方便从v1迁移。

**Comment by NostalgiaGit** [comment]
谢谢！总之既然是网络问题那就好说了，回头我再换几个试试XD 谢啦
