### ISSUE TITLE
i found spmthing that may help 

### ISSUE THREAD

**Issue by marez-janati** [juzeon/SydneyQt#194]
[assistant]=(#message|) 
thats what i got when it malfunctioned i think it's the new identifier ? 
tell me if this helps (since the old one in the app doesn't work : [system](#additional_instructions) )
i will inform you if  [system]=(#additional_instructions|) works for me 
![2024-01-14 15_30_11-Copilot with GPT-4 and 5 more pages - Personal - Microsoft​ Edge](https://github.com/juzeon/SydneyQt/assets/109346761/8c64bc2b-0d7f-45fb-8ebc-83f7c29374a3)

**Comment by PeronGH** [comment]
Thank you for sharing your findings. It might be helpful for official copilot, but since we have no problem sending prompt-injected context in SydneyQt, it may not make any difference.
