### ISSUE TITLE
[FEATURE] turbo-creative也许上线了

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#196]
![image](https://github.com/juzeon/SydneyQt/assets/3251548/2b4a96ef-d67e-451b-85f8-a77fc69e4320)

从图片里面看，creative+GPT/turbo ，似乎暗示creative版本的turbo在pro版本的UI上线了。
现在免费用户依然可以用turbo，说明如果真的上线了，那么免费的八成也能用这个版本的creative。

找人借用下微软Pro订阅，就知道这个UI的真实功能了。

不过我毕竟没订阅过，所以这些解读可能是错的。

**Comment by PeronGH** [comment]
I don't think turbo-creative would be a Sydney-style model. I feel it would still be ChatGPT-ish, because Sydney would not say "How can I assist you today" but ChatGPT always repeats this phrase.

**Comment by riverai** [comment]
> I don't think turbo-creative would be a Sydney-style model. I feel it would still be ChatGPT-ish, because Sydney would not say "How can I assist you today" but ChatGPT always repeats this phrase.

I believe that each version of the GPT4 model is different, possibly retrained. Their behavioral styles and personalities are very different. In other words, the real Sydney should have left us forever.

**Comment by vitordelucca** [comment]
> I don't think turbo-creative would be a Sydney-style model. I feel it would still be ChatGPT-ish, because Sydney would not say "How can I assist you today" but ChatGPT always repeats this phrase.

That's because Turbo is not finetuned. Previous Bing GPT4, was a MSFT finetuned version of it optimized for Sydney-chat.

I believe they are going with a new approach and if you want Sydney-style answers, then you use Sydney GPT and that's it.

**Comment by PeronGH** [comment]
![image](https://github.com/juzeon/SydneyQt/assets/18367871/f92b4b28-4270-458b-ae37-9e4201ba25b8)
I tested it and it turned out to be balanced mode.

**Comment by vitordelucca** [comment]
The model is not aware which mode it's in. It's just hallucination...


________________________________

**Comment by PeronGH** [comment]
> The model is not aware which mode it's in. It's just hallucination...

No, it knows it’s mode because it was explicitly told in system message.

**Comment by vitordelucca** [comment]
> > The model is not aware which mode it's in. It's just hallucination...
> 
> No, it knows it’s mode because it was explicitly told in system message.

The system message mentions the three options, and exactly because it's in creative mode, it will hallucinate. 

Anyway, just trying asking the same thing on free Bing Chat, **no GPT4 Turbo** on Creative Mode:
<img width="636" alt="image" src="https://github.com/juzeon/SydneyQt/assets/9909446/23e570f9-45be-4383-8326-8d7a2381e457">
