### ISSUE TITLE
[BUG] Image generation produces white images

### ISSUE THREAD

**Issue by EmPiFree** [juzeon/SydneyQt#197]
### Checks

- [X ] I confirm that I have searched existing issues and couldn't find a similar bug.
- [X ] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

I use SydneyQt with default settings.
When I tell Sydney to create an image, she tells me that she can create an image.

The created image is completly white.

With the cookies I use, I can create images on https://copilot.microsoft.com/

### To Reproduce
1. Install SydneyQt with default settings
2. Tell Sydney to create an image
3. The created image is white
4. The tab "Images" says: "No generative images available."

### Expected behavior
The image should be visible and not white

### Screenshots
![image](https://github.com/juzeon/SydneyQt/assets/22915116/6f74273e-9c88-4cc7-a793-fa23bed89239)

![image](https://github.com/juzeon/SydneyQt/assets/22915116/fc821fe4-6475-4346-8497-151402ed9057)

![image](https://github.com/juzeon/SydneyQt/assets/22915116/691f682e-d61a-4de8-9322-fe7b17cfa2c9)

### Desktop (please complete the following information):
 - OS and Version: Windows 10
 - SydneyQt Version: 2.2.6

**Comment by PeronGH** [comment]
Actually with no search, Bing doesn't generate image. It will just use markdown to reference external images or use base64 to represent an image, which may fail. You should enable search and retry.

**Comment by EmPiFree** [comment]
> Actually with no search, Bing doesn't generate image. It will just use markdown to reference external images or use base64 to represent an image, which may fail. You should enable search and retry.

Turning on search, makes no difference:
![image](https://github.com/juzeon/SydneyQt/assets/22915116/d7d92cc8-f234-477f-9f6f-4f9810b730a0)

**Comment by EmPiFree** [comment]
Alright, I could fix it. Turning on wasn't enough. I also had to create a new chat. Thanks! :)
