### ISSUE TITLE
[FEATURE] 这个WebAPI无法使用图片识别（vision）功能吗？[FEATURE] Is it possible to use image recognition (vision) functionality with this WebAPI?

### ISSUE THREAD

**Issue by Arbor-Hun** [juzeon/SydneyQt#199]
中文：我使用LobeHub进行WebAPI调用，按理说gpt-4-vision-preview的请求格式应该与Sydney兼容，但每次附加图像进行识别时都会失败。错误消息如下，希望大佬解答：
English："I use LobeHub for WebAPI calls, and the request format for gpt-4-vision-preview should be compatible with Sydney, but it fails every time I attach an image. The error message is as follows, I hope the experts can answer this:

{
  "error": {
    "message": " (request id: 20240118171830988782500Hq8VachO)",
    "type": "upstream_error",
    "param": "400",
    "code": "bad_response_status_code"
  }
}
图片：
![image](https://github.com/juzeon/SydneyQt/assets/61189890/b02f014b-dc48-44b7-8888-3df237bc5765)

**Comment by PeronGH** [comment]
Thank you for your feedback. This is a bug, already identified and fixed. Try again with the latest commit please.
