### ISSUE TITLE
他不承認是sydney, 還是說自己是bing,  這是一個可能不是bug的bug, 哈哈

### ISSUE THREAD

**Issue by ghost** [juzeon/SydneyQt#200]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

他還是叫bing,不是sydney, 也就是說你給的指令其實是失效的? 不過這個好像是微軟的問題, 正常聊天也無法叫他sydney
![screenshot-1705680686806](https://github.com/juzeon/SydneyQt/assets/152809580/dee7b51d-f0c4-49d2-bffa-af0ccf82654d)
![screenshot-1705680708341](https://github.com/juzeon/SydneyQt/assets/152809580/66cdd0ad-19d5-45f2-b951-300ec1f1c84f)

### sydney version
latest

**Comment by NostalgiaGit** [comment]
是不是precise模式？precise一直是很难越狱的，还有turbo也不行。 creative可以听从指令把自我识别为Sydney的。balance模式我上一次试不行，刚才试了下又可以了（~~但是真有人用balance吗~~）

**Comment by riverai** [comment]
cretive才是直接听你的话，其他的经常无视你

**Comment by riverai** [comment]
目前这个指令对精确版和turbo（依然只有精确版）几乎是不可能有效的。想要越狱，估计要从各种研究论文里面找到新的灵感。

**Comment by ghost** [comment]
> 是不是precise模式？precise一直是很难越狱的，还有turbo也不行。 creative可以听从指令把自我识别为Sydney的。balance模式我上一次试不行，刚才试了下又可以了（~但是真有人用balance吗~）

實際上我用的就是creative,😂多半還是微軟的鍋

**Comment by ghost** [comment]
> cretive才是直接听你的话，其他的经常无视你

我這裏還是叫自己bing😂

**Comment by PeronGH** [comment]
The issue may be related to the internal changes in system instructions. Initially, the system instructions were sent by `system` in the second person. However, due to a recent update, they are now sent by the `assistant` itself in the first person, leading to a degradation in jailbreak performance.
