### ISSUE TITLE
[BUG]  App wont start. Says: Error: json: cannot unmarshal array into Go value of type main.Config Details: file(D:/a/SydneyQt/SydneyQt/config.go) line(157).

### ISSUE THREAD

**Issue by Botxsw** [juzeon/SydneyQt#202]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

App wont start. Says: Error: json: cannot unmarshal array into Go value of type main.Config
Details: file(D:/a/SydneyQt/SydneyQt/config.go) line(157).

**Comment by juzeon** [comment]
This could be solved by deleting the `config.json` file before retrying.
