### ISSUE TITLE
[BUG] Openai后端的时候生成标题有三个问题（疑问）

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#204]
![image](https://github.com/juzeon/SydneyQt/assets/3251548/25402ac3-adef-436e-a5a5-6563d1f67409)

第一个问题，如果是OpenAI后端，是否会调用OpenAI后端来生成标题？这样做是不是有点太浪费了，因为bing可以白嫖。
第二个问题，是OpenAI后端的时候生成的标题，几乎肯定会有图片里面这种<>符号。
第三个问题，OpenAI后端生成标题的时候，似乎还是头重脚轻，应该是整个提示词都被发送了过去吧？我不确定这点，但是目前从行为来看比较符合。（新加）

**Comment by juzeon** [comment]
会调用当前工作区的后端来生成标题。如果在OpenAI调用Bing的后端，可能这时候Bing有CAPTCHA未解决，会生成失败。

第二个问题是模型本身不够智能，把内部框选的标签也给写进去了。

第三个问题，逻辑都是一样的，应该还是模型自身的问题。
