### ISSUE TITLE
[FEATURE] 多后端管理能力

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#207]
网上提供GPT4 和GPT4 32K，以及GPT4 turbo白嫖的地方还不少。

目前qt客户端的后端管理能力有点弱，如果我想同时使用多个OpenAI后端且自由切换不同（仅限少数几个有价值的）模型，其实还挺麻烦的。

**Comment by juzeon** [comment]
目前没有此项计划，若有需求建议可自己部署 [one-api](https://github.com/songquanpeng/one-api)。
