### ISSUE TITLE
SydneyQt Browser Extension

### ISSUE THREAD

**Issue by juzeon** [juzeon/SydneyQt#209]
I'm happy to announce that a browser extension for SydneyQt is under development now.

Link: <https://github.com/juzeon/SydneyQt-browser-extension>

Currently we have functions including resolving CAPTCHA and exporting cookies (to substitute the Cookie-Editor plugin).

The extension communicates with our desktop client via HTTP REST API, so remember to open the client first before using functions like updating cookies.

Feel free to test and give me feedback via [issues](https://github.com/juzeon/SydneyQt-browser-extension/issues) :)

**Comment by ThePatriotsXOF** [comment]
very cool, it would be nice if you also create an android port.

**Comment by riverai** [comment]
没有导出文件选项吗？那网页版怎么用

**Comment by juzeon** [comment]
Mark this as deprecated since we are using built-in CAPTCHA resolver now.
