### ISSUE TITLE
[Error] "InvalidRequest": "Non-Pro users do not have access to the CreativeClassic Tone."

### ISSUE THREAD

**Issue by Chagoo-nev** [juzeon/SydneyQt#213]
Version: 2.3.0
Platform: Windows

Before updating to version 2.3.0, I was able to use the "Creative Mode" without any issues, and also I can access copilot web use Creative Mode.

After updating the software to version 2.3.0, whenever I attempt to use the "Creative Mode," I receive an error message stating: "Non-Pro users do not have access to the CreativeClassic Tone." Using Webapi same error.
![screenshot-20240202-181459](https://github.com/juzeon/SydneyQt/assets/149573209/ba78e8de-8c94-43f9-920d-575f36aeb518)

ANYbody can help? Really appreciate it.

**Comment by juzeon** [comment]
Would you try switching on/off the turbo switch and see if it works?

**Comment by NostalgiaGit** [comment]
Same problem here. It will work for me if I switch on the turbo option. However, I think this is not the real turbo mode, this is the creative itself.

That's another thing that I want to mention, I think the turbo option is not working now. I tried to ask the model about something that happened in 2022 in the turbo mode (turbo+creative, balance or precise), and it didn't know. (For example, ask it who won the Qatar world cup).

**Comment by juzeon** [comment]
Microsoft now allows only turbo in creative mode for pro users, hence no option for that. So for pro:
- CreativeClassic: Old GPT-4
- Creative: Turbo

Other users would only have Creative mode but it's the old gpt-4 model.

**Comment by NostalgiaGit** [comment]
Thanks, so the turbo is only for the Pro users now, right? Non-Pro users do not have access to the turbo model now, no matter in creative, balance, or precise mode.

So the only remaining problem is that we cannot use the classic creative mode without turning on the turbo switch, as shown in the screenshot above. Although it can be easily resolved by turning on the turbo switch.

**Comment by ThePatriotsXOF** [comment]
I agree it does works with turbo on however every response sydney make it pops up ```InternalError": "Unhandled Exception``` but next prompting still works well

```

**Comment by juzeon** [comment]
Resolved via 19a0ae2025329be4e63b64dfe1f5da514ca5fba6
