### ISSUE TITLE
[FEATURE] 新的平衡模式测试机会

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#214]
刚才发现平衡模式更换了基础模型，质量似乎不错。
然后我测试了我的其中一个bing账号，似乎刚好也处在这个模式。

不知道是参数上有什么变化导致了进入测试，还是微软在后台直接决定的？

老铁要不要看看自己的账号，或者看看我的账号的情况。

https://twitter.com/vitor_dlucca/status/1753529849266733143

我自己的账号测试结果：

![image](https://github.com/juzeon/SydneyQt/assets/3251548/53811275-bf0a-4bda-9b37-d3ff83ef7e3a)

![image](https://github.com/juzeon/SydneyQt/assets/3251548/b539ded3-676f-4f2d-9389-588c71f6697a)

**Comment by riverai** [comment]
{"arguments":[{"source":"cib","optionsSets":["nlu_direct_response_filter","deepleo","disable_emoji_spoken_text","responsible_ai_policy_235","enablemm","dv3sugg","autosave","iyxapbing","iycapbing","galileo","uquopt","enflst","enpcktrk","rcaldictans","rcaltimeans","gndlogcf","sportsagrd","eredirecturl","saharagenconv5","gldcl1p"],"allowedMessageTypes":["ActionRequest","Chat","ConfirmationCard","Context","InternalSearchQuery","InternalSearchResult","Disengaged","InternalLoaderMessage","Progress","RenderCardRequest","RenderContentRequest","AdsQuery","SemanticSerp","GenerateContentQuery","SearchQuery","GeneratedCode"],"sliceIds":["newzi","ntbkf1","abv2cl","bcentbk","mobntbk","ntbk","qnacnc","codecreatorcf","v6voice","291encacheas0","cmcalltf","specedgecf","tts5","designer2cf","defcontrol","msgchkcf","116langwbs0","124multi2ts0","927storev2s0","0131dv1","0131onthdas0","sportsagrd","0131gndbfprs0","enter4nlcf"],"verbosity":"verbose","scenario":"SERP","plugins":[{"id":"c310c353-b9f0-4d76-ab0d-1dd5e979cf68","category":1}],"traceId":"65be1eb0c24041a6810dde940f4474fc","conversationHistoryOptionsSets":["autosave","savemem","uprofupd","uprofgen"],"isStartOfSession":false,"requestId":"00272dcc-f527-5867-d358-7c0cec3bbad6","message":{"locale":"zh-CN","market":"zh-CN","region":"TW","location":"lat:47.639557;long:-122.128159;re=1000m;","locationHints":[{"SourceType":1,"RegionType":2,"Center":{"Latitude":24.14189910888672,"Longitude":120.68060302734375},"Radius":24902,"Name":"Central District, Taichung City","Accuracy":24902,"FDConfidence":0.800000011920929,"CountryName":"Taiwan","CountryConfidence":8,"Admin1Name":"Taichung City","PopulatedPlaceName":"Central District","PopulatedPlaceConfidence":8,"PostCodeName":"400","UtcOffset":8,"Dma":0}],"userIpAddress":"125.227.84.74","timestamp":"2024-02-03T19:08:24+08:00","author":"user","inputMethod":"Keyboard","text":"your response is good ,can you give me more","messageType":"Chat","requestId":"00272dcc-f527-5867-d358-7c0cec3bbad6","messageId":"00272dcc-f527-5867-d358-7c0cec3bbad6"},"tone":"Balanced","spokenTextMode":"None","conversationId":"51D|BingProd|0D8A349A1493E70F7EEED23BD762BE795AAB6BABC590E5BA7ADC635B8EFC6F6C","participant":{"id":"985156939477398"}}],"invocationId":"9","target":"chat","type":4}

**Comment by riverai** [comment]
一些回答测试。

<img width="901" alt="ad8a7dc0ea60fadb7277176d013b04c" src="https://github.com/juzeon/SydneyQt/assets/3251548/49f85ced-216d-4466-ae3e-f12917f8a3d8">
<img width="910" alt="112db9765ca05133be831ff2d48362f" src="https://github.com/juzeon/SydneyQt/assets/3251548/b9dbec8a-bce3-4671-80f5-ee36dc7bd39b">
<img width="945" alt="f345bea76eb88c65d101a1cb614d220" src="https://github.com/juzeon/SydneyQt/assets/3251548/2c74d7d2-5d99-4bf3-9894-c4a28956604a">
<img width="1596" alt="c5ce3a42ed34239170bb9be3d9024b2" src="https://github.com/juzeon/SydneyQt/assets/3251548/d366fb10-c7ca-4536-8c3c-2a6685589018">


目前来看，非常像是经典GPT4的平衡版本。
 我在客户端用的老版本的平衡版，基本较为稳定的会答错，所以客户端尽快适配下还是很不错的。

7月份之后的bing创意版特别容易出现幻觉和给出特别特别非主流的观点（比3月份的创意版差很多），精确版又特别懒惰，这个平衡版是目前最好用的。

**Comment by juzeon** [comment]
测试发现应该是这个参数：`gldcl1p`

**Comment by juzeon** [comment]
加入这个参数会强制开启GPT-3.5，因此也只能给balanced用了。
