### ISSUE TITLE
[BUG]  Error Pops Up When Sydney Makes A Response ```InternalError": "Unhandled Exception```

### ISSUE THREAD

**Issue by ThePatriotsXOF** [juzeon/SydneyQt#215]
### Checks

- ☑ I confirm that I have searched existing issues and couldn't find a similar bug.
- ☑ I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

Responses does work very fine with no issues however an error pops up every response sydney make. ```"InternalError": "Unhandled Exception```

https://github.com/juzeon/SydneyQt/assets/150899804/9beeeff8-42e7-4309-bb2e-562d55dab8e2

### Desktop (please complete the following information):
 - OS and Version: [Windows 11]
 - SydneyQt Version: [v2.3.1]

**Comment by juzeon** [comment]
Seems like a bug on bing's side. Does this occur in v2.3.0?

**Comment by ThePatriotsXOF** [comment]
yes it happened on the previous version too.

**Comment by Pocarai** [comment]
> Seems like a bug on bing's side. Does this occur in v2.3.0?

Same happened in v2.3.1, I thought it is in the app or Hardware Issue 
![image](https://github.com/juzeon/SydneyQt/assets/96225118/1dfc3fc1-bd0a-49c5-9696-3c377ed69028)

**Comment by ubranch** [comment]
![image](https://github.com/juzeon/SydneyQt/assets/97873844/b1e6a250-f78f-40ce-a7f0-8f769ef88af0)
same

**Comment by jschmudd** [comment]
Same thing happens with the web api when no search is false. And with that it just closes out the connection after returning the error, no response is given. At least that's the case for the openai styled endpoint.

**Comment by jschmudd** [comment]
@juzeon  Figured it out. It is the deuct3 option that is causing the error to occur. Idk what that option does though. Removing it causes everything to work fine.

**Comment by juzeon** [comment]
@jschmudd Thanks dude.
