### ISSUE TITLE
[FEATURE] 建议

### ISSUE THREAD

**Issue by ghost** [juzeon/SydneyQt#216]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar proposal.
- [x] I have read the documentation and test the software carefully and confirmed that this is not an existing feature.

### Is your feature request related to a problem? Please describe.
使用https://copilot.microsoft.com   的接口而不是sydney.bing.com

**Comment by juzeon** [comment]
This could be changed via settings.
