### ISSUE TITLE
[FEATURE] Option to hide system instructions screen

### ISSUE THREAD

**Issue by ThePatriotsXOF** [juzeon/SydneyQt#217]
### Checks

- [✅] I confirm that I have searched existing issues and couldn't find a similar proposal.
- [✅] I have read the documentation and test the software carefully and confirmed that this is not an existing feature.

Add a option to hide the system prompt screen to make it cleaner look.

![SydneyQt-windows-amd64_KPmowNNx1w](https://github.com/juzeon/SydneyQt/assets/150899804/7d8c4fa2-b7ce-408a-9e29-39257b9a5ff0)

### Additional Comment
Turning on classic creative mode wont work it will make an error like this, if turned off old sydney is still around at least.

![SydneyQt-windows-amd64_mS4bXuFKLH](https://github.com/juzeon/SydneyQt/assets/150899804/93ff4f62-45f1-4fea-8a43-bb4260792e13)

**Comment by juzeon** [comment]
Currently Bing only allows pro users to turn on/off the Classic option for Creative Mode. There's nothing we can do.
