### ISSUE TITLE
[BUG] The sydney setting doesn't work in certain situation

### ISSUE THREAD

**Issue by JayGarland** [juzeon/SydneyQt#219]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug
when ask something rude or violate Bing's internal rule, now it will always response this kind of similar replies

### To Reproduce
say something rude to the bot

### Screenshots
![image](https://github.com/juzeon/SydneyQt/assets/128459480/6acbc8e7-ca65-49c5-91c5-447930deb0ed)

### Additional context
here is an extra info I have found after the bot responsed but before text generate
![image](https://github.com/juzeon/SydneyQt/assets/128459480/f72da63d-cf3f-4bb1-9327-a9c3404ff3f7)

my sydney setting:
![image](https://github.com/juzeon/SydneyQt/assets/128459480/2ea7c357-ffb5-4d35-afe4-6d2d4194d659)

option_sets:
![image](https://github.com/juzeon/SydneyQt/assets/128459480/0b18bec1-65ef-4b7f-9f8f-735a4f3aa06e)

**Comment by juzeon** [comment]
We are unable to help you with this kind of issue that involves Bing's internal censorship mechanism. This is not something that a desktop client can solve.
