### ISSUE TITLE
当我发送内容后出现了‘type object 'Chatbot' has no attribute 'create'’这样的问题

### ISSUE THREAD

**Issue by sundog77** [juzeon/SydneyQt#22]
<img width="1041" alt="image" src="https://github.com/juzeon/SydneyQt/assets/113448835/13e78190-b08e-4589-a35c-ed2adee933dd">
纯小白一个非it行业，当我输入内容发送后提示‘type object 'Chatbot' has no attribute 'create'’
控制台显示
File "D:\SydneyQt-master\main.py", line 298, in send_message
    chatbot = await Chatbot.create(cookies=cookies, proxy=proxy if proxy != "" else None)
                    ^^^^^^^^^^^^^^
AttributeError: type object 'Chatbot' has no attribute 'create'
但是我已经复制cookies到cookies.json中了

**Comment by juzeon** [comment]
请尝试一下按照制定issue的方式能否解决。
