### ISSUE TITLE
[FEATURE] 自动生成标题的后端可定义或者用默认bing

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#222]
现在我添加了5个OpenAI后端，轮流着白嫖turbo。
不过它们几乎都有个共同特点，就是限制了turbo的调用次数，按照次数进行限制。

就如同上次说的一样，用turbo来生成标题是真的太奢侈了。

能否改下：手动指定一个后端，比如其中一个后端的3.5或者4模型来生成标题，或者直接用白嫖的bing，毕竟这个生成标题是最好用的。

**Comment by juzeon** [comment]
不打算加这个功能，原因之前提到了，使用OpenAI后端的时候Bing可能处于未解决验证码或未登录等状态。

077c73164b71a687275393306e3e82ea29791692 增加了一个开关用于关闭自动生成标题。
