### ISSUE TITLE
[FEATURE] Add gpt4tmncnp Option For GPT-4-Turbo

### ISSUE THREAD

**Issue by jschmudd** [juzeon/SydneyQt#223]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar proposal.
- [x] I have read the documentation and test the software carefully and confirmed that this is not an existing feature.

### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
Add `gpt4tmncnp` to optionset to add new implementation of GPT-4-Turbo for everyone including free users.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by juzeon** [comment]
May I ask where you found the option? Really appreciated.

**Comment by jschmudd** [comment]
Someone mentioned it here on the [bing subreddit](https://www.reddit.com/r/bing/comments/1auigv3/comment/kr5tuhg/?utm_source=share&utm_medium=web2x&context=3)  @juzeon

**Comment by juzeon** [comment]
Great thanks dude.
