### ISSUE TITLE
[FEATURE] 模型能细分一下吗

### ISSUE THREAD

**Issue by jzysl623** [juzeon/SydneyQt#224]
参照这个

https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI

<!DOCTYPE html>
gpt-3.5-turbo | 默认为 1temperature ∈ [0, 0.75] = Precisetemperature ∈ (0.75, 1.25) = Balancedtemperature ∈ [1.25, 2] = Creative
-- | --
gpt-4-turbo-preview | 默认为 1temperature ∈ [0, 0.75] = Precise-g4ttemperature ∈ (0.75, 1.25) = Balanced-g4ttemperature ∈ [1.25, 2] = Creative-g4t
Precise | 精准模式, 联网搜索
Balanced | 平衡模式, 联网搜索
Creative | 创造模式, 联网搜索
Precise-offline | 精准模式, 不联网搜索
Balanced-offline | 平衡模式, 不联网搜索
Creative-offline | 创造模式, 不联网搜索
Precise-g4t | GPT4-Turbo 精准模式, 联网搜索
Balanced-g4t | GPT4-Turbo 平衡模式, 联网搜索
Creative-g4t | GPT4-Turbo 创造模式, 联网搜索
Precise-g4t-offline | GPT4-Turbo 精准模式, 不联网搜索
Balanced-g4t-offline | GPT4-Turbo 平衡模式, 不联网搜索
Creative-g4t-offline | GPT4-Turbo 创造模式, 不联网搜索

**Comment by juzeon** [comment]
模型选择和No Search、GPT-4-Turbo这些开关是分开的，不必排列组合了。

**Comment by jzysl623** [comment]
又增加了个notebook 支持18k 又是一个模型吧

**Comment by juzeon** [comment]
已经测试过了，底层模型实际上并不支持更长的上下文，超出部分会直接截断。
