### ISSUE TITLE
[BUG] 无限转圈

### ISSUE THREAD

**Issue by ghost** [juzeon/SydneyQt#225]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug
无限转圈

### To Reproduce
打开软件后输入问题点发送会无限转圈，网页版没问题，也没验证码，软件是最新版，全局

### Desktop (please complete the following information):
 - OS and Version: [e.g. Windows 10]
 - SydneyQt Version: [e.g. v2.2.2]

### Additional context
![企业微信截图_20240222111252](https://github.com/juzeon/SydneyQt/assets/138294823/594a3255-b142-47b4-9df2-974adf1e386d)

**Comment by juzeon** [comment]
1. 是否有弹出一个浏览器显示验证码？
2. 本地是否安装了谷歌浏览器（必须是谷歌浏览器，edge不行）。
3. 根据图上的显示，未正确导入cookie。请正确导入一遍。

**Comment by ghost** [comment]
好了，是有个人机验证
