### ISSUE TITLE
[BUG] Wails exit with status in Linux

### ISSUE THREAD

**Issue by ghost** [juzeon/SydneyQt#229]
### Checks

- [ x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [ x] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

When I try to use `wails build` in the `SydneyQt` folder it cannot open a file called build.

### To Reproduce
1. Go to `SydneyQt` in terminal.
2. Type `wails build`
3. See error

### Expected behavior
I don't know what to expect since this is my first time installing.

### Screenshots
(https://ibb.co/nzJDL29)

### Desktop (please complete the following information):
 - OS and Version: Linux Mint 21.3
 - SydneyQt Version: v2.4.3

**Comment by juzeon** [comment]
Would you confirm:
- Node.js is installed.
- All permissions are set.

Or just grab a binary from the release.

**Comment by ghost** [comment]
Node.js is installed:

![2024-03-03_10-57](https://github.com/juzeon/SydneyQt/assets/114013393/8cbab7e9-6c1b-456e-8aed-eb9524b23081)

I don't know how to check the permissions.

Also I downloaded the Linux files in releases but couldn't open it.

**Comment by juzeon** [comment]
For the binary file would you:
- chmod +x *binary-file-name-here*
- ./*binary-file-name-here*

And see what happens.

**Comment by ghost** [comment]
Yup that worked, thanks!
