### ISSUE TITLE
Should I be concerned? 

### ISSUE THREAD

**Issue by codeXXjs** [juzeon/SydneyQt#231]
I want to know why my Windows10 Def is flagging it as a Trojan. This happens when the captcha tries to load. 
![Capture](https://github.com/juzeon/SydneyQt/assets/118744203/4b50394e-568f-44ef-95bc-eedb7aaaa984)

**Comment by juzeon** [comment]
It is a component of [go-rod](https://github.com/go-rod/rod), which is introduced to power a chrome browser to resolve CAPTCHA. As far as I'm concerned it's safe to use for its open source nature.

**Comment by codeXXjs** [comment]
Okay I looked into go-rod source. Everything is fine. Thanks for clarifying
