### ISSUE TITLE
[FEATURE]  Code Interpreter Support

### ISSUE THREAD

**Issue by ThePatriotsXOF** [juzeon/SydneyQt#232]
Apparently microsoft recently added an ability to analyze files similar from chatgpt plus.

![librewolf_8CGwQ7VN3Y](https://github.com/juzeon/SydneyQt/assets/150899804/2fba07e3-bd41-489e-bbde-c9f19590523c)

**Comment by juzeon** [comment]
8d4f3b720675d4bc56574ece047d2c14f72a100d
