### ISSUE TITLE
[Feature] All file support for code interperter

### ISSUE THREAD

**Issue by ThePatriotsXOF** [juzeon/SydneyQt#233]
I appreciate that you did add a code interpreter to sydneyqt however its only limited to selected files, I kinda need sometimes to modify audio, archive packages and etc.

**Comment by juzeon** [comment]
Bing limits file types that can be uploaded. All are already added.

**Comment by ThePatriotsXOF** [comment]
> Bing limits file types that can be uploaded. All are already added.

Ah, thats a bummer well at least it does the job.
