### ISSUE TITLE
[BUG] 生成的标题需要过滤下非法文件名

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#237]
目前生成的标题直接保存的时候呢，比较容易出现因为一些特殊符号无法保存到磁盘。

估计需要对LLM说不要使用这些违规文件名或者手动过滤下。

前两天碰到了不少的例子，但是没注意保存，现在也找不到他们了。

**Comment by juzeon** [comment]
需要提供几个例子。
