### ISSUE TITLE
[BUG] Cookies Are Expired Even After Renewing

### ISSUE THREAD

**Issue by ghost** [juzeon/SydneyQt#238]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

I get the cookies from the Bing using the Cookie-Editor in Firefox, Chrome and Edge respectively, but every time I create a new cookies.json file it still says "Error: cannot identify current user, please check if cookie is expired."

### To Reproduce
1. Open `bing.com`
2. Open Cookie-Editor extension
3. Export the cookies as .json
4. Create `cookies.json` file and paste the cookies
5. Open SydneyQt
6. See error

### Expected behavior
It supposed to read the cookies

### Screenshots
![Screenshot from 2024-03-06 17-49-52](https://github.com/juzeon/SydneyQt/assets/114013393/9142958c-5eb7-4e06-aca4-ba3be0ad40b3)z

### Desktop (please complete the following information):
 - OS and Version: Linux Mint 21.3 Cinnamon 6.0.4
 - SydneyQt Version: v2.5.0

### Additional context
I also tried getting cookies from Copilot and search results but they gave me the same results.

**Comment by juzeon** [comment]
Hi,
1. Does this occur in previous versions?
2. Does the chatbot work actually?

**Comment by ghost** [comment]
Hello,

1. Yes it does. I tried every version up to 2.4.0 and it occurred in every single version.
2. I cannot confirm it because whenever I touch the drop-down menus (back-end, mode, preset, locale) or follow-up user input, app freezes.

**Comment by ghost** [comment]
>     2. Does the chatbot work actually?

I switched to wayland instance and drop-down menus are working. I tested the chatbot and I can say it works while the error continues.

**Comment by juzeon** [comment]
Would you cd to the directory and `./SydneyQt-linux-amd64` instead of double click?

**Comment by ghost** [comment]
I did that and it gave me this error in terminal when I refresh cookies:
2024/03/12 19:53:45.826904 WARN [req] ignore empty proxy url in SetProxyURL

**Comment by eapiova** [comment]
Same error in OS Windows 11 Pro

**Comment by ASOwnerYT** [comment]
You need to sign in to Bing or Copilot, then export the cookies once signed in. Worked for me.

The error message should be changed to ask the user to sign in before exporting cookies

**Comment by eapiova** [comment]
> You need to sign in to Bing or Copilot, then export the cookies once signed in. Worked for me.
> 
> The error message should be changed to ask the user to sign in before exporting cookies

Thanks, this fixed it
