### ISSUE TITLE
[BUG] 使用客户端后服务器IP会被拉黑

### ISSUE THREAD

**Issue by ghost** [juzeon/SydneyQt#242]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug
使用客户端后服务器IP会被拉黑，网页版会显示正在尝试连接，只有Andord的copilot客户端正常。

### To Reproduce
使用syqt客户端，随便问一个问题，比如你好，接着网页版就不能用了，无限重连，大概1-2天后就好了

### Screenshots
![企业微信截图_20240314105838](https://github.com/juzeon/SydneyQt/assets/138294823/3f071580-31df-4ea6-8d29-d8b627ebea6f)

### Desktop (please complete the following information):
 - OS and Version: [e.g. Windows 10] windows 11
 - SydneyQt Version: [e.g. v2.2.2]2.5.0

**Comment by juzeon** [comment]
https://github.com/juzeon/SydneyQt?tab=readme-ov-file#wss-reverse-proxy
