### ISSUE TITLE
[BUG] bing explicit error: value: Throttled; message: Request is throttled.

### ISSUE THREAD

**Issue by ThePatriotsXOF** [juzeon/SydneyQt#247]
x  I confirm that I have searched existing issues and couldn't find a similar bug.
x  I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

Cannot message bing chat because of this error.

version 2.5.1
OS: Windows 11

https://github.com/juzeon/SydneyQt/assets/150899804/d3030443-299c-41e3-bca9-aff3fbe05722

**Comment by juzeon** [comment]
You may hit daily limit. Please use another account for the time being.
