### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by known543** [juzeon/SydneyQt#251]
![Screenshot 2024-04-23 112742](https://github.com/juzeon/SydneyQt/assets/167847130/7559b1fc-234b-432b-b1a3-dd88c7142c9e)
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### Desktop (please complete the following information):
 - OS and Version: [e.g. Windows 10]
 - SydneyQt Version: [e.g. v2.2.2]

**Comment by juzeon** [comment]
Please check your network connection.
