### ISSUE TITLE
[BUG] Images are not displaying after generating, asisstant only sends the code of the picture

### ISSUE THREAD

**Issue by zeroxx021** [juzeon/SydneyQt#252]
### Checks

- [ x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [ x] I have read the documentation carefully and it couldn't resolved my problem.

### Desktop (please complete the following information):
 - OS and Version: [Windows 10]
 - SydneyQt Version: [v2.5.3]

### Additional context
<img width="890" alt="SydneyQt-windows-amd64_f9pl3AdZlJ" src="https://github.com/juzeon/SydneyQt/assets/65491720/77714d2e-717f-49bc-bd81-1f9fe4d45007">

**Comment by zeroxx021** [comment]
@juzeon

**Comment by juzeon** [comment]
You may go to the `Rich` tab to view images.

**Comment by zeroxx021** [comment]
thanks a lot
