### ISSUE TITLE
Captcha screen related to leakless.exe

### ISSUE THREAD

**Issue by patyarishimai** [juzeon/SydneyQt#256]
I'm not a technical expert of any kind so I will try to describe the issue as detailed as possible. 

Something pretty weird happened to me while using the SydneyQt application. I started getting a "solving captcha" message in the app suddenly after entering a prompt which, the instant I sent said prompt, would make windows defender pop-up a notification regarding a trojan from the /temp/ folder. After following the path I noticed it lead to a file called "leakless.exe" which, I presume, might be related to the SydneyQt processes? I conducted a search regarding the file and it appears to be a github project which, I guess, aids SydneyQt to work somehow.

https://github.com/ysmood/leakless/tree/

I tried to fix the problem by myself and, after giving an exclusion, in windows defender, to the folder where leakless.exe was archived, SydneyQt started to work again. Could the .exe might be a false-positive?

I wonder if Microsoft did something with the latest update of windows defender or if the process is actually a trojan.

**Comment by juzeon** [comment]
Please check out https://github.com/juzeon/SydneyQt/issues/231

**Comment by patyarishimai** [comment]
> Please check out #231

Got it! I thought it was a new issue for the fact that it appeared suddenly. Would keep the folder in "exclusions", thanks @juzeon keep the answer work!
