### ISSUE TITLE
Authentication failed  报错问题

### ISSUE THREAD

**Issue by echothesky** [juzeon/SydneyQt#26]
尝试过更换cookie，但没有起作用，后台报错如下
![image](https://github.com/juzeon/SydneyQt/assets/106248959/4faf444f-02c9-4647-b682-21d35077b816)
希望大佬能在百忙之中抽空解答，非常感谢

**Comment by juzeon** [comment]
登到网页上聊一句然后再导出cookie。

**Comment by echothesky** [comment]
> 登到网页上聊一句然后再导出cookie。

很高兴能得到您的解答，在得到您的回复后试过了，很遗憾仍然不奏效，报错还是一样

**Comment by juzeon** [comment]
按照 <https://github.com/juzeon/SydneyQt/issues/17#issuecomment-1571206228> 的方法设置一下代理。

**Comment by for3ever3** [comment]
> 按照 [#17 (comment)](https://github.com/juzeon/SydneyQt/issues/17#issuecomment-1571206228) 的方法设置一下代理。

解决了，thanks
