### ISSUE TITLE
[BUG] Crashing after tabbing out then tabbing back in

### ISSUE THREAD

**Issue by buranyaa** [juzeon/SydneyQt#265]
### Checks

- [x] I confirm that I have searched existing issues and couldn't find a similar bug.
- [x] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug

When tabbing out (Alt+Tab), the app is normally running in the background but when tabbing back in, the app immediately crashes. This also happens when inserting or selecting a file to upload. It also doesn't necessarily have to be tabbing out, even clicking outside of the app then going back in will crash it.

### To Reproduce
1. Tab out
2. Tab back in
or
1. Open another app
2. Go back into SydQT

### Expected behavior
I expected that the app wouldn't be crashing whenever switching apps.

### Desktop (please complete the following information):
 - OS and Version: Windows 11 23H2
 - SydneyQt Version: v2.5.4

**Comment by juzeon** [comment]
Hi please check if this would be of help: https://github.com/juzeon/SydneyQt/issues/133
