### ISSUE TITLE
大佬可否添加免费的GPT4的API支持

### ISSUE THREAD

**Issue by PoseidonLi0514** [juzeon/SydneyQt#32]
大佬可否添加免费的GPT4的API支持，我自己弄的四不像。https://discord.gg/b8EwrWwg 这是那个提供API的discord地址，然后里面有examples 他里面有gpt4的各种模型都可以调用，并且API几乎不限制。我本来想自己搞的，结果发现能力不够，大佬帮帮忙吧，谢谢大佬了

**Comment by PoseidonLi0514** [comment]
![image](https://github.com/juzeon/SydneyQt/assets/58305290/bb8de138-e43b-4811-a09c-498bd6fc98b3)
`import openai

openai.api_key = "your API KEY from `/key get` Discord command"
openai.api_base = "https://chimeragpt.adventblocks.cc/v1"

response = openai.ChatCompletion.create(
    model='gpt-4',
    messages=[
        {'role': 'user', 'content': "Hello"},
    ],
    stream=True
)

for chunk in response:
    print(chunk.choices[0].delta.get("content", ""), end="", flush=True)`
这是我的key `THrm-CmGYg4STCKF2qdA5HgZtMD_q09CgQd5EzetOKg`

**Comment by juzeon** [comment]
看样子用的是官方的API风格。那么只要在设置中把endpoint改成`https://chimeragpt.adventblocks.cc/v1`这个，API Key改成他提供的这个就行了。聊天的时候`Backend`选择ChatGPT。

**Comment by PoseidonLi0514** [comment]
> 看样子用的是官方的API风格。那么只要在设置中把endpoint改成这个，API Key改成他提供的这个就行了。聊天的时候选择ChatGPT。`https://chimeragpt.adventblocks.cc/v1``Backend`

OK,成功了，谢谢大佬！！顺便大佬想问一下什么情况下会切换到Long Model

**Comment by juzeon** [comment]
> > 看样子用的是官方的API风格。那么只要在设置中把endpoint改成这个，API Key改成他提供的这个就行了。聊天的时候选择ChatGPT。`` https://chimeragpt.adventblocks.cc/v1``Backend ``
> 
> OK,成功了，谢谢大佬！！顺便大佬想问一下什么情况下会切换到Long Model

token数超过阈值（threshold）的时候。

**Comment by G-LJDS2022** [comment]
> > 看样子用的是官方的API风格。那么只要在设置中把endpoint改成这个，API Key改成他提供的这个就行了。聊天的时候选择ChatGPT。`` https://chimeragpt.adventblocks.cc/v1``Backend ``
> 
> OK，成功了，谢谢大佬！！顺便大佬想问一下什么情况下会切换到Long Model

怎么弄的，能详细说一下吗，谢谢

**Comment by G-LJDS2022** [comment]
![1689251645145](https://github.com/juzeon/SydneyQt/assets/134282368/10ffe61e-b01f-4779-825c-f9d8fad11a97)
![147171fda0642e25c9a37d87574b0f0](https://github.com/juzeon/SydneyQt/assets/134282368/26b2fd11-b5c2-4a87-aa08-1afc99af0ffb)

**Comment by G-LJDS2022** [comment]
> 

兄弟，你怎么弄的，能教一下吗？

**Comment by liangxyz** [comment]
请问楼主怎么过的那个Double Counter的验证？我被检测到vpn了
