### ISSUE TITLE
User needs to solve captcha to continue, it doesnt show captcha,

### ISSUE THREAD

**Issue by RoseCoon** [juzeon/SydneyQt#34]
![binggg](https://github.com/juzeon/SydneyQt/assets/134891687/def3ebf0-7c69-4973-8cbf-172c00dc80b6)

Hello, so whenever I try to send a message it says "Captcha challenge, user needs to solve captcha to continue" and im not sure what to do, because it doesnt show the captcha and i tried closing the application, i deleted the files and reinstalled it, I upgraded the edge gpt, i tried to use cookies, I restarted my computer, but it keep showing this message and I cant chat with it if its keep giving me this message. Im sorry if this is a dumb questions, but i need your help. Please and thank you.

**Comment by juzeon** [comment]
Please open your browser and chat with Bing AI online, then try again.

**Comment by Shiroy0** [comment]
Same problem, 😀

**Comment by juzeon** [comment]
When you chat with the Bing AI on the web, it may show a captcha if required. The captcha will be solved automatically, and the cookies will be updated. Just replace the old cookies with the new ones. If that doesn't work, please try registering a new Microsoft account and do the same. You may also need to try different proxy nodes.

**Comment by AISIS7** [comment]
The EdgeGPT has been updated. The older EdgeGPT which sydneyqt uses gives captcha error. Please fix the sydneyqt project by updating to the latest EdgeGPT version.

**Comment by RoseCoon** [comment]
Okay, So it works! thank you everyone for helping me!! I just upgraded the edgeGPT and chatted with bing to update my cookies then it worked!

**Comment by AISIS7** [comment]
It solved for me too. But then, it is again giving me capcha's. I have to do it everytime now to update my cookies. I tried the update EdgeGPT and it works fine. Captcha issue is only a problem with older EdgeGPT versions which this project is using sadly.

**Comment by RoseCoon** [comment]
> It solved for me too. But then, it is again giving me capcha's. I have to do it everytime now to update my cookies. I tried the updated EdgeGPT and it works fine. Captcha issue is only a problem with older EdgeGPT versions which this project is using sadly.

Yeah, it worked for a while, but now sometimes it works and sometimes it doesn't even if i update my cookies, and when i try to chat to bing.com it rarely gives me any captcha, so that's a problem. But as I'm writing this, its not working.

**Comment by juzeon** [comment]
> It solved for me too. But then, it is again giving me capcha's. I have to do it everytime now to update my cookies. I tried the updated EdgeGPT and it works fine. Captcha issue is only a problem with older EdgeGPT versions which this project is using sadly.

Could you please make sure your proxy IP is consistent and matches the one you use on the Bing AI web?
EdgeGPT does not have a way to deal with captcha. Besides, the latest versions of EdgeGPT have dropped jailbreak support. Check out https://github.com/acheong08/EdgeGPT/issues/88
