### ISSUE TITLE
每次使用前都要先和bing chat聊天，才能解决验证码问题，怎么才能一劳永逸？

### ISSUE THREAD

**Issue by G-LJDS2022** [juzeon/SydneyQt#43]
每次使用前都要先和bing chat聊天，才能解决验证码问题，怎么才能一劳永逸？有人说升级EdgeGPT可以解决，但好像有人说升级最新版的EdgeGPT后，不能越狱开启Sydney模式，真的吗？

**Comment by juzeon** [comment]
保持每次使用的代理IP一致即可。

最新版EdgeGPT不支持越狱。
