### ISSUE TITLE
'int' object has no attribute 'split'

### ISSUE THREAD

**Issue by lemonstable** [juzeon/SydneyQt#45]
这是什么问题呢

**Comment by juzeon** [comment]
See [FAQ](https://github.com/juzeon/SydneyQt#faq).

**Comment by renqabs** [comment]
最新版的EdgeGPT应该是修了这个bug（通过重发请求），这个问题好像是因为没收到服务端响应消息
![image](https://github.com/juzeon/SydneyQt/assets/130155002/35774be9-130c-42ce-b9e8-66fb9fa08be4)
