### ISSUE TITLE
修复图片生成的bug

### ISSUE THREAD

**Issue by renqabs** [juzeon/SydneyQt#46]
ask_stream方法，在raw=True时处理存在问题，可以参考修复下（新版的edgegpt跟当前项目里的用的函数不太一样，慎重修改），主要是GenerateContentQuery这个一般在response type为1的消息里，如果不处理的直接返回的话就不会生成图片了，当然，生成了图片也要对响应消息做相应的解析才可以得到图片
https://github.com/acheong08/EdgeGPT/pull/582/commits/d6058506c6ae87c69da0414ee9f26c46ecdf8594

**Comment by juzeon** [comment]
若方便可否提交个PR？谢谢！

**Comment by renqabs** [comment]
edgegpt部分我还可以改改，但是qt部分我确实不太懂，我现在基本都用的黑暗大佬的chatsydney。。。

**Comment by renqabs** [comment]
我试了一下，太难了，我改不动，代码太老了，我也不知道哪里出了问题，建议还是升级到原版的EdgeGPT吧，我目前的chatsydney用的0.11.8 EdgeGPT以及SydneyGPT 0.11.8一样可以越狱，但是也有会别的bug。。。

**Comment by NijikaMyWaifu** [comment]
https://github.com/juzeon/SydneyQt/pull/47

**Comment by renqabs** [comment]
![image](https://github.com/juzeon/SydneyQt/assets/130155002/f8bcba32-5317-445c-a67b-deb248fde144)

**Comment by juzeon** [comment]
Fixed by 44267b55c21ac5a321463c77d658bc1fbdbf8077. Help close this issue if this is what you want.
