### ISSUE TITLE
200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')

### ISSUE THREAD

**Issue by G-LJDS2022** [juzeon/SydneyQt#49]
How to solve the problem that just came up today?

**Comment by juzeon** [comment]
It seems that New Bing has tightened its IP detection mechanism. We are currently using a random forward IP like this:

```python
_FORWARDED_IP = f"1.0.0.{random.randint(0, 255)}"
```

However, it seems that this method is no longer working. Can you access New Bing in the browser with the same proxy IP that you use in the client? If not, please try a different proxy server that can bypass the New Bing restriction.

**Comment by juzeon** [comment]
Commit 11c2c498f1fe8763b518fbc6ed38f6195811a799 fixed the issue. See README for new proxy setup with Cloudflare Workers.
