### ISSUE TITLE
SyntaxError:invalid syntax

### ISSUE THREAD

**Issue by Frypies** [juzeon/SydneyQt#5]
![1684113748227](https://github.com/juzeon/SydneyQt/assets/89576861/b3d0c052-2cf5-4395-aef6-1ccc80a5e0ea)
很不错，相比其他项目设置更方便，在win10上能测试通过。
win7上会报错SyntaxError:invalid syntax，还请作者大大看一下这个。

**Comment by juzeon** [comment]
因为用了match语法，所以需要python 3.10及更高的版本。
