### ISSUE TITLE
WHAT happened and how to solve it

### ISSUE THREAD

**Issue by PsychoticGao** [juzeon/SydneyQt#51]
0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

**Comment by juzeon** [comment]
Could you solve this by following the 4th step in the Usage section and the FAQ section? Another option is to change your proxy node.

**Comment by PsychoticGao** [comment]
can you help me ,i have fix the dev as the Usage say, but it also remind me 0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

**Comment by PsychoticGao** [comment]
![Snipaste_2023-07-13_15-47-37](https://github.com/juzeon/SydneyQt/assets/129344875/8a566fca-155a-4e95-9796-49edf98d669e)

**Comment by PsychoticGao** [comment]
我看有中文留言，我省着组织语言了哈哈，我每次发都会 给我这样的提示
![Snipaste_2023-07-13_15-47-37](https://github.com/juzeon/SydneyQt/assets/129344875/13310a45-011e-497c-9ddb-5a69cddbca29)

**Comment by PsychoticGao** [comment]
我改了代理后就会提示拒绝访问

**Comment by juzeon** [comment]
这个接口是创建会话的接口，不是接受聊天内容的wss接口，按理来说只要有代理就都能创建。应该是Clash（代理服务器、端口等）的问题，请检查一下。

**Comment by PsychoticGao** [comment]
不是就把这个dev复制到wssdomain那一栏就行吗~



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 13, 2023 15:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [juzeon/SydneyQt] WHAT happened and how to solve it (Issue #51)




 
这个接口是创建会话的接口，不是接受聊天内容的wss接口，按理来说只要有代理就都能创建。应该是Clash（代理服务器、端口等）的问题，请检查一下。

**Comment by PsychoticGao** [comment]
请教是哪一步呢？



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 13, 2023 20:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [juzeon/SydneyQt] WHAT happened and how to solve it (Issue #51)




 
我同样的问题，按照指南解决了

**Comment by PsychoticGao** [comment]
> 我同样的问题，按照指南解决了

你好，能不能看一下你的设置啊~谢谢

**Comment by PsychoticGao** [comment]
我这里json也设置了，cookies也导出了，替换那不知道怎么弄，因为发现隐私模式根本上不了bing剩下的方法都试过了

**Comment by PsychoticGao** [comment]
改了proxy后就会弹出错误
![Snipaste_2023-07-13_21-53-37](https://github.com/juzeon/SydneyQt/assets/129344875/ee66da36-94c7-4761-bde1-62f8ceb6ce37)

**Comment by PsychoticGao** [comment]
貌似是被重定向了，www.bing.com会被定向为cn.bing.com

**Comment by G-LJDS2022** [comment]
就是按照作者今天更新的说明一步一步操作的

**Comment by PsychoticGao** [comment]
我昨天试了v2和clash都这样报错，v2我还可以上bing呢，clash就不行，能不能请教怎么设置



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 13, 2023 15:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [juzeon/SydneyQt] WHAT happened and how to solve it (Issue #51)




 
这个接口是创建会话的接口，不是接受聊天内容的wss接口，按理来说只要有代理就都能创建。应该是Clash（代理服务器、端口等）的问题，请检查一下。
