### ISSUE TITLE
Brother, can you support unofficial OpenAI API?

### ISSUE THREAD

**Issue by G-LJDS2022** [juzeon/SydneyQt#53]
![1689250243818](https://github.com/juzeon/SydneyQt/assets/134282368/6862b1c5-ba9c-4d0f-8b29-21348e030ada)
https://gptgod.site/api/v1/chat/completions,

**Comment by G-LJDS2022** [comment]
To add on, the unofficial OpenAI API endpoint is [POST]https://gptgod.site/api/v1/chat/completions, the interface format refers to OpenAI's completions API。

**Comment by G-LJDS2022** [comment]
![1689251645145](https://github.com/juzeon/SydneyQt/assets/134282368/4b70c0b0-312a-4ee3-bd94-37c054a4a274)
![147171fda0642e25c9a37d87574b0f0](https://github.com/juzeon/SydneyQt/assets/134282368/61685b01-9320-4c52-a699-04dc531150ce)

**Comment by juzeon** [comment]
Try replacing the existing `OpenAI Endpoint` value with `https://gptgod.site/api/v1`.
