### ISSUE TITLE
启动main.py报错

### ISSUE THREAD

**Issue by oswald521** [juzeon/SydneyQt#54]
\SydneyQt-master\sydney.py", line 205, in <module>
    proxy: str | None = _PROXY,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by oswald521** [comment]
修好了，改成了proxy: Union[str, None] = _PROXY,cookies: Union[List[Dict], None] = None,

**Comment by juzeon** [comment]
建议使用Python 3.10以上版本。
