### ISSUE TITLE
Enter key makes newline 2 times

### ISSUE THREAD

**Issue by Eikosa** [juzeon/SydneyQt#57]
Enter key makes newline 2 times. It happens when I do it with shift + enter or numpad enter. The problem only happens in press enter to send mode
Example:
![image](https://github.com/juzeon/SydneyQt/assets/20538090/104ad3de-aa3e-4e99-a99c-acb8d7355c55)

**Comment by juzeon** [comment]
Could you please provide your system and environment information?
Also you can change the send key from the dropdown menu of the Send button and use Enter for linebreaks and Ctrl + Enter for sending.

**Comment by Eikosa** [comment]
When I delete this line the problem is fixed, I don't understand what this line does.
![image](https://github.com/juzeon/SydneyQt/assets/20538090/1db2ea4f-14a0-49ea-9687-8f4b60919c27)

**Comment by Eikosa** [comment]
Windows 11
Python 3.10.9
