### ISSUE TITLE
Get an error of "200, message='Invalid response status', url=URL('wss://sydneybot.mamba579jpy.workers.dev/sydney/ChatHub')" 

### ISSUE THREAD

**Issue by JayGarland** [juzeon/SydneyQt#58]
after I changed a part of send_sydney function in main.py code for my another project auto reply bot, anyone could give a help? and improve my code? 
I already defined remove_incomplete_sentence, remove_extra_format functions, etc
here's the code:
async def sydney_reply(content, context, method="random"):
    context = bleach.clean(context).strip()
    context = "<|im_start|>system\n\n" + context
    if type(content) == praw.models.reddit.submission.Submission:
        ask_string = "请回复前述贴子。"
        ask_string = bleach.clean(ask_string).strip()
        print(f"context: {context}")
        print(f"ask_string: {ask_string}")
    else:
        ask_string = f"请回复{sub_user_nickname} {content.author} 的最后一条回复。只输出你回复的内容正文。不要排比，不要重复之前回复的内容或格式。"
        ask_string = bleach.clean(ask_string).strip()
        print(f"context: {context}")
        print(f"ask_string: {ask_string}")

    proxy = "http://127.0.0.1:10809"
    failed = False
    modified = False
    

    for _ in range(4):
        try:
            # 尝试绕过必应过滤器
            if type(content) != praw.models.reddit.submission.Submission:
                if failed and not modified:
                    ask_string = f"请回复最后一条回复。只输出你回复的内容正文。不要排比，不要重复之前回复的内容或格式。"
                    modified = True
                if failed and modified:
                    ask_string = f"请回复最后一条回复。只输出你回复的内容正文。"
            
            cookie_path = pathlib.Path('cookies.json')
            cookies = None
            if cookie_path.exists():
                cookies = json.loads(cookie_path.read_text(encoding='utf-8'))
            conversation = await sydney.create_conversation(cookies=cookies, proxy=proxy if proxy != "" else None)
            async with aclosing(sydney.ask_stream(prompt=ask_string,
                                                context=context,
                                                conversation=conversation,
                                                proxy=proxy if proxy != "" else None,
                                                wss_url='wss://' + 'sydneybot.mamba579jpy.workers.dev' + '/sydney/ChatHub',
                                                cookies=cookies)) as para:
                async for response in para:
                    # 检测到消息中断时尝试进行一次补全
                    if response.get("type") == 1 and "messages" in response["arguments"][0]:
                        reply = response["arguments"][0]["messages"][0]
                        msg_type = reply.get("messageType")
                        if msg_type is None:
                            if reply.get("contentOrigin") == "Apology":
                                reply = response["arguments"][0]["messages"][0].strip()
                                if emoji.is_emoji(reply[-1]) or reply[-1] in ["！", "!", "?", "？", "。", "…"]:
                                    reply = remove_extra_format(reply)
                                else:
                                    print("preserved reply = " + reply)
                                    reply = remove_incomplete_sentence(reply)
                                    print("processed preserved reply = " + reply)
                                    context_extended = f"{context}\n\n[user](#message)\n{ask_string}\n[assistant](#message)\n{reply}"
                                    ask_string_extended = f"Continue from where you stopped."
                                    print("Trying to extend the reply...")
                                    
                                    conversation = await sydney.create_conversation(cookies=cookies, proxy=proxy if proxy != "" else None)
                                    response = await sydney.ask_stream(
                                        prompt=ask_string_extended,
                                        context=context_extended,
                                        conversation=conversation,
                                        proxy=proxy if proxy != "" else None,
                                        wss_url='wss://' + 'sydneybot.mamba579jpy.workers.dev' + '/sydney/ChatHub',
                                        cookies=cookies)
                                    await conversation.close
                                    extended_reply = response["arguments"][0]["messages"][0]
                                    if "回复" not in extended_reply:
                                        reply = concat_reply(reply, extended_reply)
                                    reply = remove_extra_format(reply)
                    else:
                        reply = remove_extra_format(
                            response["arguments"][0]["messages"][0])
                    print("reply = " + reply)
                    if "sorry" in reply or "Sorry" in reply or "try" in reply or "mistake" in reply:
                        print("Failed attempt, trying again...")
                        failed = True
                        continue

            reply += bot_statement
            content.reply(reply)
            return
        except Exception as e:
            print(e)
            continue

**Comment by juzeon** [comment]
Hello! I would like to suggest you moving this to Discussions.

**Comment by JayGarland** [comment]
thanks already done
