### ISSUE TITLE
PySide6==6.5.0 版本不存在

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#60]
依赖中是这样写的，但是我测试用pip更换了几个源都说找不到这个版本。

PS X:\SydneyQt-master> pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple/
Collecting EdgeGPT==0.8.1
  Using cached EdgeGPT-0.8.1-py3-none-any.whl (14 kB)
ERROR: Could not find a version that satisfies the requirement PySide6==6.5.0 (from versions: 6.0.0a1.dev1606913934, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.2.0, 6.2.1, 6.2.2, 6.2.2.1, 6.2.3, 6.2.4, 6.3.0, 6.3.1, 6.3.2, 6.4.0)
ERROR: No matching distribution found for PySide6==6.5.0

**Comment by juzeon** [comment]
你好，官方源中有这个版本 https://pypi.org/project/PySide6/6.5.0/

**Comment by riverai** [comment]
> 你好，官方源中有这个版本 https://pypi.org/project/PySide6/6.5.0/
> 
> 建议卸载Python重装一下3.x的最新版。

好不容易找到了36版本 安装包卸载了以前的版本，然后直接把以前的lib文件夹删除了，再把环境变量手动清理了。
然后安装了311版本，也确认添加了环境变量到path，还确认这个路径是path里面排第一，但是：
每次输入Python，都会自动跳转到Windows store，当真莫名其妙，完全毫无头绪。

不知道你有没有经验呢？之前36Python本来一切都好好的。现在311怎么看怎么对，就是不能运行。

**Comment by juzeon** [comment]
> > 你好，官方源中有这个版本 https://pypi.org/project/PySide6/6.5.0/
> > 建议卸载Python重装一下3.x的最新版。
> 
> 好不容易找到了36版本 安装包卸载了以前的版本，然后直接把以前的lib文件夹删除了，再把环境变量手动清理了。 然后安装了311版本，也确认添加了环境变量到path，还确认这个路径是path里面排第一，但是： 每次输入Python，都会自动跳转到Windows store，当真莫名其妙，完全毫无头绪。
> 
> 不知道你有没有经验呢？之前36Python本来一切都好好的。现在311怎么看怎么对，就是不能运行。

重启一下系统，然后在命令行输入`where python`或者`where python3`看看用的是哪个路径的python。

**Comment by riverai** [comment]
> > > 你好，官方源中有这个版本 https://pypi.org/project/PySide6/6.5.0/
> > > 建议卸载Python重装一下3.x的最新版。
> > 
> > 
> > 好不容易找到了36版本 安装包卸载了以前的版本，然后直接把以前的lib文件夹删除了，再把环境变量手动清理了。 然后安装了311版本，也确认添加了环境变量到path，还确认这个路径是path里面排第一，但是： 每次输入Python，都会自动跳转到Windows store，当真莫名其妙，完全毫无头绪。
> > 不知道你有没有经验呢？之前36Python本来一切都好好的。现在311怎么看怎么对，就是不能运行。
> 
> 重启一下系统，然后在命令行输入`where python`或者`where python3`看看用的是哪个路径的python。

既没有报错，也没有运行，毫无提示。
心态崩溃，我还是等系统哪天自己好吧。

**Comment by juzeon** [comment]
可以试一试用python.exe所在的绝对路径启动Python。

**Comment by riverai** [comment]
> 每次输入Python，都会自动跳转到Windows store，当真莫名其妙，完全毫无头绪。

谢谢！这个办法可以，pip和Python终于运行起来了。
然后项目也跑起来了。
