### ISSUE TITLE
0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

### ISSUE THREAD

**Issue by nahedehesafa** [juzeon/SydneyQt#63]
0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

**Comment by juzeon** [comment]
See [FAQ](https://github.com/juzeon/SydneyQt#faq).

**Comment by nahedehesafa** [comment]
File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 588, in _request
    raise TooManyRedirects(
aiohttp.client_exceptions.TooManyRedirects: 0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

**Comment by SXtar37** [comment]
What do you do? I have a same error.
PLEASE
头大了T-T
