### ISSUE TITLE
自动reset 提示词

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#65]
目前，在preset选择了一个预设之后，还需要每次都再点击下actions 中的reset应用更改。

在用户消息未提交之前，也就是刚刚开始聊天的时候，能否将这个功能自动化呢？

**Comment by juzeon** [comment]
没有办法知道用户是否是在刚刚开始聊天的状态，因为用户可能会更改additional_instructions里的值，如果直接reset会覆盖掉用户改动的内容。

**Comment by riverai** [comment]
> 没有办法知道用户是否是在刚刚开始聊天的状态，因为用户可能会更改additional_instructions里的值，如果直接reset会覆盖掉用户改动的内容。

真的毫无办法吗？有没有变通的方法呢。

比如，新建了Workspace之后，如果还没有提交任何消息，那么就肯定还没开始聊天。
这种时候，用户要么是自己现场编写additional_instructions，要么就是选择一个preset然后应用。对于后面选择preset的人而言，选择跟reset应用是几乎一回事，选择了就一定会应用，不然何必去选择一个preset呢。
