### ISSUE TITLE
不要强行锁定对话框到最后一行

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#67]
现在对话的时候，如果对方在打字输出文字，那么对话框是会被强行锁定到最后一行。哪怕我将进度条往上拉，也会瞬间回复到最后一行的状态。

导致的后果，就是消息完全没法看了，因为文字一直在强制更新，最后一行又总是被锁定，所以文字一直在抖动，根本看不清楚。

期望的行为，是对方在打字的时候，我可以选择向上拉动，然后我慢慢看不会一直抖动的文字。

如果能做下这个修改，可读性又要好多了。

**Comment by JayGarland** [comment]
Will work it out by commenting line of code "self.chat_history.moveCursor(QTextCursor.MoveOperation.End)" within "append_chat_context" "stream_output" function in main.py file

**Comment by juzeon** [comment]
You can click the Snap button to see a snapshot of the current chat context.

**Comment by riverai** [comment]
> 

确实是个办法，但是如果停止了总是追踪到最后一行这功能，或者像bing网页版那样，只要滚轮向上滚动，就会停止追踪最后一行而保持在滚轮移动的位置，那么会远远更方便。
