### ISSUE TITLE
（新问题，bing无法验证）CaptchaChallenge: User needs to solve CAPTCHA to continue

### ISSUE THREAD

**Issue by G-LJDS2022** [juzeon/SydneyQt#68]
现在出现“CaptchaChallenge: User needs to solve CAPTCHA to continue”这个错误后，再用浏览器打开bing chat进行聊天，不弹出验证窗口了，不验证就无法使用。

**Comment by riverai** [comment]
听说最近一周，bing开始封锁各种机房IP，很容易中枪。

**Comment by juzeon** [comment]
可能是cookies.json中的cookies过期了，更新一下即可。
