### ISSUE TITLE
打开就闪退

### ISSUE THREAD

**Issue by deepsleepless** [juzeon/SydneyQt#70]
cmd打开
Traceback (most recent call last):
  File "D:\SydneyQt-master\main.py", line 10, in <module>
    from contextlib import aclosing
ImportError: cannot import name 'aclosing' from 'contextlib' (D:\a3\lib\contextlib.py
版本3.9.13
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
直接打开显示这个

**Comment by juzeon** [comment]
请更新Python到最新版本。

**Comment by deepsleepless** [comment]
^^^^^^^^^^^^^^^^^^^^^
  File "D:\py\Lib\site-packages\aiohttp\client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SydneyQt-master\main.py", line 433, in send_sydney
    conversation = await sydney.create_conversation(cookies=cookies, proxy=proxy if proxy != "" else None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SydneyQt-master\sydney.py", line 227, in create_conversation
    raise Exception(text)
Exception

**Comment by deepsleepless** [comment]
Expecting value: line 1 column 1 (char 0)

**Comment by deepsleepless** [comment]
我是直接f12把cookie复制出来会有问题吗

**Comment by riverai** [comment]
手动复制肯定不如用插件复制，后者方便太多。而且插件是用JSON标准写好的，你手动复制不知道是不是。

**Comment by deepsleepless** [comment]
用了微软的Cookie-Editor好像还是不行

**Comment by deepsleepless** [comment]
[Errno 2] No such file or directory: 'cookies.json'
Traceback (most recent call last):
  File "D:\SydneyQt-master\sydney.py", line 224, in create_conversation
    conversation = await response.json()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\py\Lib\site-packages\aiohttp\client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SydneyQt-master\main.py", line 433, in send_sydney
    conversation = await sydney.create_conversation(cookies=cookies, proxy=proxy if proxy != "" else None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SydneyQt-master\sydney.py", line 227, in create_conversation
    raise Exception(text)
Exception

**Comment by deepsleepless** [comment]
手动选cookie的json文件能识别current user但是没啥用

**Comment by juzeon** [comment]
`cookies.json`应放在与`main.py`同级目录下，启动时cmd的pwd也应在`main.py`的目录下。

**Comment by deepsleepless** [comment]
Traceback (most recent call last):
  File "D:\SydneyQt-master\main.py", line 433, in send_sydney
    conversation = await sydney.create_conversation(cookies=cookies, proxy=proxy if proxy != "" else None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SydneyQt-master\sydney.py", line 216, in create_conversation
    response = await session.get(
               ^^^^^^^^^^^^^^^^^^
  File "D:\py\Lib\site-packages\aiohttp\client.py", line 588, in _request
    raise TooManyRedirects(
aiohttp.client_exceptions.TooManyRedirects: 0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

**Comment by deepsleepless** [comment]
部署好了，还是这个报错

**Comment by deepsleepless** [comment]
调试连接已关闭。原因：websocket已断开连接。准备就绪时，打开devtools即可重新连接。cloudflare里有这个，是这个问题吗
