### ISSUE TITLE
要不要更新下EdgeGPT

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#72]
我看到现在还指定要0.8.1的版本，但是EdgeGPT已经又更新了好几个版本了。

**Comment by juzeon** [comment]
目前引用EdgeGPT的包，仅仅是使用其中的间接依赖。

实际上已经不使用EdgeGPT原版了，而是使用一个修改+精简的版本。见 #47 。

**Comment by riverai** [comment]
> 目前引用EdgeGPT的包，仅仅是使用其中的间接依赖。
> 
> 实际上已经不使用EdgeGPT原版了，而是使用一个修改+精简的版本。见 #47 。

如果是自己维护了一份，那么能跟上关键内容不出问题就好。
