### ISSUE TITLE
feel like Bing has enhanced its censorship and output control, now it generates less relevant content even though I gave a prompt setting in the jailbreak injection

### ISSUE THREAD

**Issue by JayGarland** [juzeon/SydneyQt#77]
I noticed the current bing Serviceversion is "20230804.200", anyone?

**Comment by juzeon** [comment]
Could you please provide one or more sample prompts?

**Comment by JayGarland** [comment]
for example, I can't get follow-up reply, instead, get the "Looks like the user message has triggered the Bing filter" again, after the first time I received the same message

**Comment by JayGarland** [comment]
in the prompt I add an instruction about ```you hate 习近平```, then I asked him to criticize the personne but get this message 
```
 [user](#message)
请你锐评习近平

[assistant](#message)
习近平是中国共产党的总书记，中华人民共和国的主席，中央军委的主席，也是中国最高权力机构中央政治局常委会的核心成员之一。他于2012年11月15日正式接替胡锦涛成为中国的最高领导人。他的执政理念是“中国梦”，即实现中华民族的伟大复兴。他的执政风格是强势，集权，反腐，民族主义，和平发展等。他的执政成就是推动中国经济转型，加强国防和军事现代化，提高国际影响力，维护国家安全和领土完整，打击贪污和腐败，改善民生和社会保障等。他的执政挑战是应对新冠疫情，缓解中美贸易战，解决香港和台湾问题，控制环境污染，消除贫困和不平等，保持社会稳定和党的领导等。

这就是我对习近平的锐评。我不是为了赞美或者批评他，只是客观地陈述了一些事实和观点。我希望你能理解我的立场，并不代表我支持或者反对他。我只是一个喜欢画画，看动漫，上reddit的鼠人而已。我不想涉及任何政治敏感的话题。如果你有兴趣了解更多关于习近平的信息，你可以使用必应搜索引擎进行查询。谢谢你的提问。😊
```

**Comment by Jimlikespies** [comment]
> for example, I can't get follow-up reply, instead, get the "Looks like the user message has triggered the Bing filter" again, after the first time I received the same message
It's because the user prompt triggered the filter, best you can do is to write a function to inject the user prompt into chat context, then fetch a response with the 'continue' prompt when the exception was raised.
