### ISSUE TITLE
Noticed there is a "SafeSearch" option in Bing website settings, does it affect the output content for this project 

### ISSUE THREAD

**Issue by JayGarland** [juzeon/SydneyQt#79]
there are three option in the "SafeSearch", Strict, Moderate, Off. 
I want the Chatbot of this project generates more adult content, if the option affect this project, can anyone help me to make it always turn the SafeSearch off?

**Comment by juzeon** [comment]
SafeSearch does not affect AI-generated content. It only relates to the search results that the AI uses.
