### ISSUE TITLE
闪退报错

### ISSUE THREAD

**Issue by etoiles22** [juzeon/SydneyQt#8]
我不会代码，请帮看一下是什么情况，谢谢，所有步骤都按照说明进行了，那个edgegpt是可以打开的，而这个打不开 ，系统是win11，版本是python3.10 64位
![UZVS8551~GMKK8V T`B1)9B](https://github.com/juzeon/SydneyQt/assets/133737897/140cc65d-a91d-4a71-bfb1-40f2f8b44e3d)

**Comment by juzeon** [comment]
没有配置`cookies.json`，请仔细看README。

**Comment by etoiles22** [comment]
好了，更新之后就没问题了，感谢！这个问题就不删了吧，更新代码挺有用的
