### ISSUE TITLE
UnauthorizedRequest: Cannot retrieve user status.

### ISSUE THREAD

**Issue by jianruifu** [juzeon/SydneyQt#81]
出现了如标题所示的问题

**Comment by juzeon** [comment]
Have you set up `cookies.json` according to the Usage section of the README file?

And also try following the instructions in the FAQ section.

**Comment by jianruifu** [comment]
您好，您的来信已收到，我将尽快给您回复。

**Comment by jianruifu** [comment]
问题解决了，谢谢您
