### ISSUE TITLE
今天出现'conversationSignature'

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#82]
之前还是用得好好的，现在突然不行了，出现了标题说的报错。

打开网页版bing，用得好好的，没发现问题。
用与网页版同样的网络节点和cookie在客户端用，就总是报这个错。

换了节点，结果是一样的。

**Comment by riverai** [comment]
现在，也就是3个小时之后，客户端又可以使用了。

这之间我没做任何操作，而是去睡了一觉，节点和cookie也没动。

**Comment by juzeon** [comment]
可能是微软服务器的锅，让我们看看这个问题是否会再次出现。

**Comment by OXERIS** [comment]
我'conversationSignature'出现后，网页版的bing chat也不能用了，感觉是不是问了过多不符合政策的问题

**Comment by OXERIS** [comment]
我觉得是我的账号被屏蔽了，我登出账号就能看到bing chat的按钮了，登录就消失

**Comment by riverai** [comment]
> 我觉得是我的账号被屏蔽了，我登出账号就能看到bing chat的按钮了，登录就消失

https://bing.com/turing/conversation/create 
你访问下这个网址，有返回成功就是依然有资格的。

说起来这个，你试试在uBlock origin添加规则清理cookie：

www.bing.com##+js(cookie-remover, ANON)
bing.com##+js(cookie-remover, ANON)

如果你有这个anon开头的cookie，网页版和客户端都没办法用。
网页版是看不到聊天界面。客户端是报错，但不是报这个签名错误。

不过你的事情倒是提醒我了，莫非我有类似的问题？至少可以说下我的猜想：

因为网页版是自然访问，同时清理了cookie所以没事。
但是依然有未知的机制识别到了第三方客户端访问，所以被用其他手段限制了客户端访问？
后来我用网页版访问过，这种限制就自动解除了，所以同样的cookie就可以用客户端访问了。

**Comment by OXERIS** [comment]
> > 我觉得是我的账号被屏蔽了，我登出账号就能看到bing chat的按钮了，登录就消失
> 
> https://bing.com/turing/conversation/create 你访问下这个网址，有返回成功就是依然有资格的。
> 
> 说起来这个，你试试在uBlock origin添加规则清理cookie：
> 
> [www.bing.com##+js(cookie-remover](http://www.bing.com##+js(cookie-remover), ANON) bing.com##+js(cookie-remover, ANON)
> 
> 如果你有这个anon开头的cookie，网页版和客户端都没办法用。 网页版是看不到聊天界面。客户端是报错，但不是报这个签名错误。
> 
> 不过你的事情倒是提醒我了，莫非我有类似的问题？至少可以说下我的猜想：
> 
> 因为网页版是自然访问，同时清理了cookie所以没事。 但是依然有未知的机制识别到了第三方客户端访问，所以被用其他手段限制了客户端访问？ 后来我用网页版访问过，这种限制就自动解除了，所以同样的cookie就可以用客户端访问了。

![image](https://github.com/juzeon/SydneyQt/assets/18722082/26884366-d656-4820-953d-f8b87a96bead)
我的访问结果如上图，有返回success

**Comment by OXERIS** [comment]
uBlock origin是什么

**Comment by OXERIS** [comment]
> > 我觉得是我的账号被屏蔽了，我登出账号就能看到bing chat的按钮了，登录就消失
> 
> https://bing.com/turing/conversation/create 你访问下这个网址，有返回成功就是依然有资格的。
> 
> 说起来这个，你试试在uBlock origin添加规则清理cookie：
> 
> [www.bing.com##+js(cookie-remover](http://www.bing.com##+js(cookie-remover), ANON) bing.com##+js(cookie-remover, ANON)
> 
> 如果你有这个anon开头的cookie，网页版和客户端都没办法用。 网页版是看不到聊天界面。客户端是报错，但不是报这个签名错误。
> 
> 不过你的事情倒是提醒我了，莫非我有类似的问题？至少可以说下我的猜想：
> 
> 因为网页版是自然访问，同时清理了cookie所以没事。 但是依然有未知的机制识别到了第三方客户端访问，所以被用其他手段限制了客户端访问？ 后来我用网页版访问过，这种限制就自动解除了，所以同样的cookie就可以用客户端访问了。

我清理完cookie能用1秒钟，我添加你的插件，加规则试试

**Comment by OXERIS** [comment]
> > 我觉得是我的账号被屏蔽了，我登出账号就能看到bing chat的按钮了，登录就消失
> 
> https://bing.com/turing/conversation/create 你访问下这个网址，有返回成功就是依然有资格的。
> 
> 说起来这个，你试试在uBlock origin添加规则清理cookie：
> 
> [www.bing.com##+js(cookie-remover](http://www.bing.com##+js(cookie-remover), ANON) bing.com##+js(cookie-remover, ANON)
> 
> 如果你有这个anon开头的cookie，网页版和客户端都没办法用。 网页版是看不到聊天界面。客户端是报错，但不是报这个签名错误。
> 
> 不过你的事情倒是提醒我了，莫非我有类似的问题？至少可以说下我的猜想：
> 
> 因为网页版是自然访问，同时清理了cookie所以没事。 但是依然有未知的机制识别到了第三方客户端访问，所以被用其他手段限制了客户端访问？ 后来我用网页版访问过，这种限制就自动解除了，所以同样的cookie就可以用客户端访问了。

试了一下，清楚cookie并添加规则后，网页版ban登录后不刷新能用，刷新以后网页版就无法访问bingchat了。把那个cookie保存下来后，py客户端倒是能用了

**Comment by riverai** [comment]
> 

没听过这种。你的规则不是每次都自动生效？ 
你再用查看cookie的插件有没有anon开头的在那里。

另外，这个技巧我上个月都用上了，直到今天出现了我最开头描述的问题。

**Comment by OXERIS** [comment]
> > 
> 
> 没听过这种。你的规则不是每次都自动生效？ 你再用查看cookie的插件有没有anon开头的在那里。
> 
> 另外，这个技巧我上个月都用上了，直到今天出现了我最开头描述的问题。

![image](https://github.com/juzeon/SydneyQt/assets/18722082/679cebd0-87c4-420e-820c-14f030e39306)
![image](https://github.com/juzeon/SydneyQt/assets/18722082/f30982d9-a607-47f9-aeb4-8327e6fbc78e)

**Comment by OXERIS** [comment]
> > 
> 
> 没听过这种。你的规则不是每次都自动生效？ 你再用查看cookie的插件有没有anon开头的在那里。
> 
> 另外，这个技巧我上个月都用上了，直到今天出现了我最开头描述的问题。

有的

**Comment by riverai** [comment]
> > > 
> > 
> > 
> > 没听过这种。你的规则不是每次都自动生效？ 你再用查看cookie的插件有没有anon开头的在那里。
> > 另外，这个技巧我上个月都用上了，直到今天出现了我最开头描述的问题。
> 
> ![image](https://user-images.githubusercontent.com/18722082/260906185-679cebd0-87c4-420e-820c-14f030e39306.png) ![image](https://user-images.githubusercontent.com/18722082/260906232-f30982d9-a607-47f9-aeb4-8327e6fbc78e.png)

不用想了，格式错误，没有正确使用。

**Comment by OXERIS** [comment]
> coo

好像你发我的规则格式也有点问题

**Comment by riverai** [comment]
> > coo
> 
> 好像你发我的规则格式也有点问题

我发的没问题，是你抄错了。

**Comment by OXERIS** [comment]
> > > coo
> > 
> > 
> > 好像你发我的规则格式也有点问题
> 
> 我发的没问题，是你抄错了。
因为我直接复制的话，报错了，我删了一个中括号，我加上试试

**Comment by OXERIS** [comment]
> > > coo
> > 
> > 
> > 好像你发我的规则格式也有点问题
> 
> 我发的没问题，是你抄错了。

因为我直接复制的话，报错了，我删了一个中括号，我加上试试

**Comment by OXERIS** [comment]
> > > > coo
> > > 
> > > 
> > > 好像你发我的规则格式也有点问题
> > 
> > 
> > 我发的没问题，是你抄错了。
> 
> 因为我直接复制的话，报错了，我删了一个中括号，我加上试试

![image](https://github.com/juzeon/SydneyQt/assets/18722082/133e18ac-e580-4cb0-bfae-8e32199cb342)
我现在不修改你提供的规则，也有anon

**Comment by riverai** [comment]
> > > > > coo
> > > > 
> > > > 
> > > > 好像你发我的规则格式也有点问题
> > > 
> > > 
> > > 我发的没问题，是你抄错了。
> > 
> > 
> > 因为我直接复制的话，报错了，我删了一个中括号，我加上试试
> 
> ![image](https://user-images.githubusercontent.com/18722082/260907398-133e18ac-e580-4cb0-bfae-8e32199cb342.png) 我现在不修改你提供的规则，也有anon

1错误提示。
注意换行。

**Comment by OXERIS** [comment]
> 

![image](https://github.com/juzeon/SydneyQt/assets/18722082/18545705-60c8-4388-87a3-23a40f0bd36b)
从chatgpt的解释来看，似乎是少了一个小括号

**Comment by OXERIS** [comment]
> > > > > > coo
> > > > > 
> > > > > 
> > > > > 好像你发我的规则格式也有点问题
> > > > 
> > > > 
> > > > 我发的没问题，是你抄错了。
> > > 
> > > 
> > > 因为我直接复制的话，报错了，我删了一个中括号，我加上试试
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/18722082/260907398-133e18ac-e580-4cb0-bfae-8e32199cb342.png) 我现在不修改你提供的规则，也有anon
> 
> 1错误提示。 注意换行。

换行以后确实好了，谢谢，原来是两条规则

**Comment by OXERIS** [comment]
> 这个anon开头的cookie

可以请教一下你是如何发现需要移除这个cookie的吗？多谢

**Comment by riverai** [comment]
> 
这个是外国网民早就发现的，我只是做了下Google搜索。

**Comment by OXERIS** [comment]
> bing.com##+js(cookie-remover, ANON)

https://www.reddit.com/r/bing/comments/14zi672/keep_getting_error_when_logged_in/

我通过搜索bing 和 anon的关键词找到了出处，但是感觉我很难用英文表述这个问题并搜索，比如原文是getting_error_when_logged_in、Can't access the "main" Bing Chat，不过我又学会了两种表述方式

**Comment by OXERIS** [comment]
弄好以后，玩了几个小时，被反复要求确认是真人。
![image](https://github.com/juzeon/SydneyQt/assets/18722082/ed111be4-2fd4-42f9-b35b-49bb16edb657)
认证虽然会成功，但是确反复让我重新开始，我感觉我是被封控了。

**Comment by juzeon** [comment]
> 弄好以后，玩了几个小时，被反复要求确认是真人。 ![image](https://user-images.githubusercontent.com/18722082/261030305-ed111be4-2fd4-42f9-b35b-49bb16edb657.png) 认证虽然会成功，但是确反复让我重新开始，我感觉我是被封控了。

试一下用Bing安卓客户端聊一句。

**Comment by OXERIS** [comment]
> > 弄好以后，玩了几个小时，被反复要求确认是真人。 ![image](https://user-images.githubusercontent.com/18722082/261030305-ed111be4-2fd4-42f9-b35b-49bb16edb657.png) 认证虽然会成功，但是确反复让我重新开始，我感觉我是被封控了。
> 
> 试一下用Bing安卓客户端聊一句。

等了一天好了，不敢再问瑟瑟的问题了，感觉再来几次真的要封号，我的安卓客户端暂时不能用。
