### ISSUE TITLE
交互上还有点小问题

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#87]
1 snap和reset太近。

reset会清空整个对话，而且没有后悔的机会。snap则是在复制和查看消息的时候经常使用。

将这两个重要功能放到一起还是相当危险的。这就相当于电影里面，将自毁按钮和启动按钮放到一起的情节。
而且我通常还需要回顾整理下消息才会删除内容。如果我真的需要新开对话，那么我真的就会新开对话，而不是在现有的对话reset，根本没有reset的需求。

对此我有个想法：

reset功能已经多余。目前，我从来没主动用过reset，如果我真的想要删除一个对话，我会选择左下角的Delete，而不是reset。

2 左下角的clear功能过于强大

clear会清理所有的对话内容，功能实在是过于强大了。
但是点一下所有内容就没了，相当于发射核弹只需要动一下手指，风险和操作上存在不对称。

对上述的一些想法：

我感觉可以把reset删除。
或者把reset移动到现在clear的位置。

这样的好处是依然保持4左下角四个按钮的对称。
如果真的有人喜欢用reset不断重置现在的内容，那么这样也不算太大的问题. 它边上就是Delete，功能相近在一起也说得过去。

clear按钮可以移动到settings中，而且加入一常见的“清空确认”流程。

**Comment by juzeon** [comment]
reset我个人还是挺经常使用的，目前为它加了个确认对话框，可以在设置里打开或关闭。

左下角的Clear是有弹框的，应该不容易误操作吧？

**Comment by riverai** [comment]
> reset我个人还是挺经常使用的，目前为它加了个确认对话框，可以在设置里打开或关闭。
> 
> 左下角的Clear是有弹框的，应该不容易误操作吧？
我觉得目前这样改动了之后也是可以接受的了。

不过我觉得我提的那种方案让类似的功能扎堆在一起，让应该出现的东西出现在应该出现的地方，更加符合直觉。

reset如果在左下角，也更加靠近输入区域，而不是显示区域，似乎也更符合直觉。

当然如果按照我的那种提议，clear误触的可能性很小，确认流程就没太多必要。
如果保持目前的布局不变，reset的确认流程就必须存在。

**Comment by riverai** [comment]
> reset我个人还是挺经常使用的，目前为它加了个确认对话框，可以在设置里打开或关闭。
> 
> 左下角的Clear是有弹框的，应该不容易误操作吧？

我又想到一种方法。
其实可以模仿bing官方的reset功能，让reset不再具有“不可恢复性“。 平时如果真的有人用reset，也就是喜欢它的便利——快速重新启用目前的提示词和环境。

既然如此，给reset加入”立即确认流程“就妨碍了这种便利性。

昨天我的一个想法是改变reset位置，防止误触也不需要确认。

现在我的想法是，如果非要保持恒定的布局，那么可以改变reset的功能，让reset的功能变成：

保存现有对话环境到历史会话。
初始化对话环境。

历史会话中的内容，可以稍后回顾下手动Delete（所谓温故而知新）。

如此就保留了reset的便利性，也增强了reset的安全型。

**Comment by juzeon** [comment]
右边四个按钮的功能都是操作工作区列表的，倘若把Reset移动到这里并替换掉Clear按钮，恐怕不妥。

如果放在User Input顶上应该是更加符合官网的设计，但那个地方已经按钮太多放不下了...而且还有其他功能比较常用的按钮，感觉还是会误触。

Reset这个功能的出现在工作区功能很早之前就有了，目的就是针对当前Chat Context进行复原。

因为我个人使用的习惯是开不同的工作区，每个工作区preset和backend都不一样，需要用哪个的时候就切过去用一下，然后reset完事；如果遇到需要存储Chat Context的话，就用当前工作区的配置新建一个工作区，把新的工作区作为之后使用，旧的工作区作为存档。

现在各家ChatGPT客户端主流的设计是每次对话都新开一个session，然后把旧的存起来放到历史对话中。长久以来历史对话就会越来越多，其中无用对话基本上占大多数，一旦想要回去找某个对话的话很难，要翻找很久。

因此我想的是用一种和主流不同的设计，由用户每次离开时决定该session是否有价值、需要保存，而不是默认保存。
