### ISSUE TITLE
可否改下默认save格式

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#89]
默认保存到了txt，结果每次都是用文本编辑器直接打开了源代码模式的Markdown文本，各种渲染效果是一个也没看到，既不美观也不怎么方便。

之前我还每次都手动改成.md结尾，但是保存多了就懒得动手了，又重新成了.txt。

所以，能否改下默认保存的格式到.md呢？
看起来能少走几分钟弯路啊。

**Comment by juzeon** [comment]
Chat Context实际上不是标准的markdown格式，例如标志角色的地方会被markdown识别成超链接，造成渲染错误。

**Comment by riverai** [comment]
确实，这个错看太久已经被我无视了。

不过，保存到.md格式，在稍微强点的md编辑器，比如Obsidian，连数学公式都可以渲染，比看莫名其妙的源代码强太多了。

居正 ***@***.***> 于2023年8月25日周五 22:12写道：
