### ISSUE TITLE
Sorry, you need to login first to access this service.请问这是什么错误导致的?

### ISSUE THREAD

**Issue by mirrordg** [juzeon/SydneyQt#9]
账号是没有问题的,登录并且聊天之后才复制了cookie,不太会用python,如果需要提供log信息麻烦大佬给一些操作提示
![Quicker_20230516_145408](https://github.com/juzeon/SydneyQt/assets/92014544/87444329-136f-44f8-8f22-0d3f94333278)

**Comment by mirrordg** [comment]
对了,第一次使用这个客户端的时候账号是有登录限制的,因为是以前的一个账号很久没用了,,刷了几次验证码才正常,然后又重新获取了一次cookie,不知道跟这个有没有关系

**Comment by juzeon** [comment]
更新下EdgeGPT版本：`pip install EdgeGPT --upgrade`。

**Comment by juzeon** [comment]
直接运行EdgeGPT的cli版本呢？

**Comment by mirrordg** [comment]
是运行acheong08那个吗？我按着他的教程到传入cookie那一步就不懂怎么操作了

**Comment by mirrordg** [comment]
是运行acheong08那个吗？我按着他的教程到传入cookie那一步就不懂怎么操作了

**Comment by juzeon** [comment]
README中`Chatbot`->`Running from the Command Line`。
