### ISSUE TITLE
当日首次对话几乎必出SSL报错

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#90]
> Cannot connect to host edgeservices.bing.com:443 ssl:default [[SSL: PACKET_LENGTH_TOO_LONG] packet length too long (_ssl.c:1002)]

每天的第一次使用，几乎肯定出SSl相关错误。然后我再次发送消息就不会有问题。

之前一阵，也有与开头类似的错误，叫作SSL version error，发生的时间也在第一次对话的时候。

不知道这是怎么回事。

**Comment by juzeon** [comment]
我这里无法复现，可能和梯子有关。

**Comment by riverai** [comment]
有可能是，以后再说。
