### ISSUE TITLE
is there a way to make Sydney generate images in context messages?

### ISSUE THREAD

**Issue by JayGarland** [juzeon/SydneyQt#92]
if possible, please update this function :)

**Comment by juzeon** [comment]
Please wait while we work on resolving issue #33 so that live rendering can be available.

**Comment by JayGarland** [comment]
can anyone improve this code? looks like it must has a valid ID

![image](https://github.com/juzeon/SydneyQt/assets/128459480/2131da23-6768-41d3-9e62-641d5e1bf903)

**Comment by juzeon** [comment]
Resolved a5812fa8e9c34cea89bbd7caa3b1f0bf6229493b.
