### ISSUE TITLE
最近用起来有点奇怪

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#93]
我用的是我自己写的一个提示词，以前的版本是这样的：https://www.yayaus.com/2023/05/17/%e8%ae%a9ai%e6%9d%a5%e5%85%85%e5%bd%93%e7%8e%b0%e4%bb%a3%e8%8b%b1%e8%af%ad%e8%af%ad%e6%b3%95%e8%80%81%e5%b8%88%e7%9a%84%e6%8f%90%e7%a4%ba%e8%af%8d.html

就在大概一周之前，每次对话，bing还都会说“我是XX，我会如何如何。。”。然后看到我发送的英文内容，会说“这段话是说了什么。。某某是简单句，某某是复合句。某某使用了被动语态，目的是...“等等。

我之前就有个发现，提示词似乎只对创意模式有效，对精确模式是无效的。
具体来说，只有创意版会出现上面的效果，精确版就好像根本没看到这些一样，直接将内容无视了，很像没有任何提示词的时候它会说话的风格。

但是，最近一周，我发现创意版也这样了，直接就无视了这种提示词的效果。

发英文内容给它，直接就会告诉我翻译内容，不会说出来任何的解析。如果手动问”你看到了提示词的内容了吗“，它又会说看到了。我问”为何你不遵循要求“，它又会重新开始按照提示词的要求来分析内容。

反正最近一周，用起来特别奇怪。

**Comment by riverai** [comment]
目前用起来就是很怪。少数时候和以前一样，多数时候就属于我一楼说的那种“好像看到了，又好像没看到“。

还是先关了再关闭几天吧。

**Comment by riverai** [comment]
现在这种感觉，我问了下朋友，不只是我一个人这样说了。
以前的时候，特别是5月份的时候，bing会告诉你，这里是复合句/简单句，这里是非谓语，这里是被动。。这里是什么。。然后目的是什么。。作用是什么。。为什么这样写。
然后说：现在回到你的问题。。问题的答案应该是。。。


它自己就会长篇大论，它自己就会自己“一步步思考”。
现在直接无视了，一句话直接打发，错误率高好多！

这里就表现出：

以前会严格遵守提示词，现在不会。很容易打发你。
以前会自动一步步思考，现在哪怕你让它这样做都可能无视。

**Comment by NostalgiaGit** [comment]
我也是之前就发现类似问题，创意模式下，在system#addtional_instructions 里注入的prompt，当规则复杂起来时，它有时会听，有时会忽略，有时又听一半，有种“如听”的感觉。不过我当时是猜测这和服务器算力有关，在负载高的时候，bing会“变笨”，于是对prompt理解的效果就会打折。

但创意模式好歹多少生效一下，而且像比如Sydney的那种比较简短的prompt它还是能理解并遵守的。但精准模式真的完全忽略system instructions，完全没法让它变Sydney，不知道是怎么回事。
