### ISSUE TITLE
今天开始疯狂出现 conversationid 错误

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#96]
<img width="190" alt="a63dfaff3080a4393a44f395060a4e8" src="https://github.com/juzeon/SydneyQt/assets/3251548/9ebb7a15-dd1d-4ed3-9909-a6111dcc6176">
现在内容要发好几次才能发出去，不知道怎么回事。

我问了下，不只是我一个人这样。

**Comment by juzeon** [comment]
尝试一下同一代理环境，若用同一账号，网页版能否正常使用？

出现这个问题的原因是服务器返回了异常的JSON：

```json
{
    "result": {
        "value": "InternalServerError",
        "message": "Error processing request."
    }
}
```

**Comment by riverai** [comment]
> 尝试一下同一代理环境，若用同一账号，网页版能否正常使用？
> 
> 出现这个问题的原因是服务器返回了异常的JSON：
> 
> ```json
> {
>     "result": {
>         "value": "InternalServerError",
>         "message": "Error processing request."
>     }
> }
> ```

之前，先是本地容易出现这个报错，网页版还是可以正常回答我问题的。
然后，本地疯狂报错，再过了一会儿总是报错，没有例外。本地完全没法用了。
现在我打开网页版，网页版一直是提示“正在重连”，完全没办法用。

不知道你那里怎样？bing自己挂了吗

**Comment by juzeon** [comment]
我的网页版也挂了，一开始是显示正在重连，现在是显示`Sorry, looks like your network settings are preventing access to this feature`。

用的已经是Cloudflare WARP的IP了。看来微软又加强了一波IP限制。

**Comment by JayGarland** [comment]
the bing still works in skype

**Comment by tugberkcapraz** [comment]
Hello, just asking to understand the situation. Are our accounts banned now?

**Comment by riverai** [comment]
> Hello, just asking to understand the situation. Are our accounts banned now?

No

**Comment by riverai** [comment]
问题自己消失了，估计是bing自己挂了。

然后，我登录我的小号，发现没有了聊天框，处于半封锁状态。
退出账号，还是没出现聊天框。
选择-清除所有bing.com cookie ，聊天框出现。
重新登录小号。可以正常使用聊天。

还有问题的按照我说的操作下就是了。
