### ISSUE TITLE
Cloudflare Workers 建立一个代理后还是 0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

### ISSUE THREAD

**Issue by SXtar37** [juzeon/SydneyQt#98]
#63 
图片：
https://i.postimg.cc/KY3TfZmy/5a892339eebbce752227ae64ac375be.png
https://i.postimg.cc/c42ZGZQH/b86223e19d44b8dfc86a4afaf03abaa.png
@juzeon

**Comment by juzeon** [comment]
如果使用Clash等代理软件，请检查bing.com走了代理。有些机场的配置文件可能会把bing.com加入到直连列表中。
