### ISSUE TITLE
是否能中途更换创意版和精确版？

### ISSUE THREAD

**Issue by riverai** [juzeon/SydneyQt#99]
之前我就有过一个想法：让创意版输出内容，最后让精确版来评估内容。
但是我测试过几次，感觉每次都基本上是自己赞同自己。

现在我再次测试了下，怀疑最后进行评估的依然是创意版自己，最后更改精确版的操作没生效。

从下面的图来看，最后用了个表情，这像是创意版的风格。
![image](https://github.com/juzeon/SydneyQt/assets/3251548/9e9c1467-7987-422b-b802-c3cd19c769cf)

**Comment by juzeon** [comment]
中途更换创意版或精确版是生效的。
